#ifndef _LEXKEY_H_
#define _LEXKEY_H_
//
//	VERBS
//
enum enumTyxVerbs {
	V_APP       =   1, // apply
	V_ARM       =   2, // arm
	V_CAL       =   3, // calculate
	V_CHN       =   4, // change
	V_CLS       =   5, // close
	V_CMP       =   6, // compare
	V_CON       =   7, // connect
	V_CPL       =   8, // couple
	V_CRE       =   9, // create
	V_DCL       =  10, // declare
	V_DEF       =  11, // define
	V_DEL       =  12, // delete
	V_DIS       =  13, // disconnect
	V_DO        =  14, // do
	V_DSB       =  15, // disable
	V_ELS       =  16, // else
	V_ENB       =  17, // enable
	V_END       =  18, // end
	V_EST       =  19, // establish
	V_FIN       =  20, // finish
	V_FOR       =  21, // for
	V_FTH       =  22, // fetch
	V_GTO       =  23, // go to
	V_IDY       =  24, // identify
	V_IF        =  25, // if
	V_INC       =  26, // include
	V_INP       =  27, // input
	V_INX       =  28, // initiate
	V_LVE       =  29, // leave
	V_MEA       =  30, // measure
	V_MON       =  31, // monitor
	V_OPN       =  32, // open
	V_OUT       =  33, // output
	V_PFM       =  34, // perform
	V_PRV       =  35, // prove
	V_RD        =  36, // read
	V_REM       =  37, // remove
	V_REQ       =  38, // require
	V_RES       =  39, // resume
	V_RST       =  40, // reset
	V_SET       =  41, // setup
	V_SNS       =  42, // sense
	V_STI       =  43, // stimulate
	V_TRM       =  44, // terminate
	V_UCP       =  45, // uncouple
	V_UPD       =  46, // update
	V_VER       =  47, // verify
	V_WHL       =  48, // while
	V_WTF       =  49, // wait for
	V_XTN       =  50, // extend
	V__CNT      =  51, // symbol count
};
//
//	NOUNS
//
enum enumTyxNouns {
	N_ACS       =   1, // ac signal
	N_ADF       =   2, // adf
	N_AMB       =   3, // ambient conditions
	N_AMS       =   4, // am signal
	N_ATC       =   5, // atc
	N_BUS       =   6, // bus protocol
	N_BUT       =   7, // button
	N_COM       =   8, // common
	N_DCF       =   9, // digital configuration
	N_DCS       =  10, // dc signal
	N_DGT       =  11, // digital test
	N_DIS       =  12, // displacement
	N_DME       =  13, // dme
	N_DOP       =  14, // doppler
	N_EAR       =  15, // earth
	N_EMF       =  16, // em field
	N_EPW       =  17, // exponential pulse wave
	N_EVS       =  18, // events
	N_EVT       =  19, // event
	N_EXC       =  20, // exchange
	N_FLU       =  21, // fluid signal
	N_FMS       =  22, // fm signal
	N_HEA       =  23, // heat
	N_IFF       =  24, // iff
	N_ILS       =  25, // ils
	N_IMP       =  26, // impedance
	N_INF       =  27, // infrared
	N_LAS       =  28, // laser
	N_LCL       =  29, // logic control
	N_LDT       =  30, // logic data
	N_LGT       =  31, // light
	N_LLD       =  32, // logic load
	N_LRF       =  33, // logic reference
	N_LTR       =  34, // laser target return
	N_MAN       =  35, // manometric
	N_MDS       =  36, // modulated signal
	N_MIF       =  37, // multi-sensor-infrared
	N_MIL       =  38, // multi-sensor-light
	N_PAC       =  39, // pulsed ac
	N_PAM       =  40, // pam
	N_PAT       =  41, // pulsed ac train
	N_PDC       =  42, // pulsed dc
	N_PDP       =  43, // pulsed doppler
	N_PDT       =  44, // pulsed dc train
	N_PMS       =  45, // pm signal
	N_RDN       =  46, // random noise
	N_RDS       =  47, // radar signal
	N_RPS       =  48, // ramp signal
	N_RSL       =  49, // resolver
	N_RTN       =  50, // rotation
	N_SCS       =  51, // sup car signal
	N_SHT       =  52, // short
	N_SIM       =  53, // simultaneous
	N_SIN       =  54, // sinc wave
	N_SQW       =  55, // square wave
	N_STM       =  56, // stepper motor
	N_STS       =  57, // step signal
	N_SYN       =  58, // synchro
	N_TAC       =  59, // tacan
	N_TDG       =  60, // timed digital
	N_TED       =  61, // turbine engine data
	N_TMI       =  62, // time interval
	N_TMR       =  63, // timer
	N_TRI       =  64, // triangular wave signal
	N_VBR       =  65, // vibration
	N_VID       =  66, // video signal
	N_VOR       =  67, // vor
	N_WAV       =  68, // waveform
	N__CNT      =  69, // symbol count
};
//
//	MODIFIERS
//
enum enumTyxModifiers {
	M_ACCF      =   1, // ac-comp-freq
	M_ACCP      =   2, // ac-comp
	M_ADFM      =   3, // add-from
	M_ADTO      =   4, // add-to
	M_AGER      =   5, // age-rate
	M_ALLW      =   6, // allowance
	M_ALTI      =   7, // alt
	M_ALTR      =   8, // alt-rate
	M_AMBT      =   9, // ambient-temp
	M_AMCP      =  10, // am-comp
	M_AMCU      =  11, // am-coupl
	M_AMFQ      =  12, // am-freq
	M_AMMC      =  13, // ampl-mod-c
	M_AMMF      =  14, // ampl-mod-f
	M_AMPL      =  15, // ampl-mod
	M_AMSH      =  16, // am-shift
	M_AMSR      =  17, // am-source
	M_ANAC      =  18, // angle-accel
	M_ANAX      =  19, // angle-accel-x
	M_ANAY      =  20, // angle-accel-y
	M_ANAZ      =  21, // angle-accel-z
	M_ANGL      =  22, // angle
	M_ANGP      =  23, // angle-phi
	M_ANGT      =  24, // angle-theta
	M_ANGX      =  25, // angle-x
	M_ANGY      =  26, // angle-y
	M_ANGZ      =  27, // angle-z
	M_ANRT      =  28, // angle-rate
	M_ANRX      =  29, // angle-rate-x
	M_ANRY      =  30, // angle-rate-y
	M_ANRZ      =  31, // angle-rate-z
	M_ANSD      =  32, // ant-speed-dev
	M_ATMS      =  33, // atmos
	M_ATTE      =  34, // attenuation
	M_ATTN      =  35, // atten
	M_AUCO      =  36, // autocollimation-error
	M_BAND      =  37, // bandwidth
	M_BARP      =  38, // barometric-press
	M_BDTH      =  39, // beam-detection-threshold
	M_BITP      =  40, // bit-period
	M_BITR      =  41, // bit-rate
	M_BLKT      =  42, // blackbody-temp
	M_BRAN      =  43, // boresight-angle
	M_BTRN      =  44, // bit-transition
	M_BURD      =  45, // burst-droop
	M_BURR      =  46, // burst-rep-rate
	M_BURS      =  47, // burst
	M_BUSM      =  48, // bus-mode
	M_BUSS      =  49, // bus-spec
	M_CAMG      =  50, // camera-gain
	M_CAMP      =  51, // car-ampl
	M_CAPA      =  52, // cap
	M_CCOM      =  53, // count-command
	M_CDAT      =  54, // count-data
	M_CFRQ      =  55, // car-freq
	M_CHAN      =  56, // channel
	M_CHCT      =  57, // chan-crosstalk
	M_CHID      =  58, // channel-ident
	M_CHIT      =  59, // chan-integrity
	M_CHRM      =  60, // car-harmonics
	M_CLKS      =  61, // clock-source
	M_CMCH      =  62, // compare-ch
	M_CMDW      =  63, // command-word
	M_CMPL      =  64, // compl
	M_CMTO      =  65, // compare-to
	M_CMWB      =  66, // command-word-bit
	M_CMWV      =  67, // compare-wave
	M_COMD      =  68, // command
	M_COND      =  69, // conductance
	M_COUN      =  70, // count
	M_CPHS      =  71, // car-phase
	M_CPKN      =  72, // current-p-neg
	M_CPKP      =  73, // current-p-pos
	M_CPLG      =  74, // coupling
	M_CRSD      =  75, // car-resid
	M_CRSF      =  76, // crest-factor
	M_CSTS      =  77, // count-status
	M_CUPK      =  78, // current-p
	M_CUPP      =  79, // current-pp
	M_CUR0      =  80, // current-zero
	M_CUR1      =  81, // current-one
	M_CURA      =  82, // av-current
	M_CURI      =  83, // current-inst
	M_CURL      =  84, // current-lmt
	M_CURQ      =  85, // current-quies
	M_CURR      =  86, // current
	M_CURT      =  87, // current-trms
	M_CWLV      =  88, // cw-level
	M_DATA      =  89, // data
	M_DATL      =  90, // data-word-length
	M_DATP      =  91, // data-word-parity
	M_DATS      =  92, // data-word-sync
	M_DATT      =  93, // data-word-tr
	M_DATW      =  94, // data-word
	M_DBLI      =  95, // dbl-int
	M_DBND      =  96, // doppler-bandwidth
	M_DBRC      =  97, // debris-count
	M_DBRS      =  98, // debris-size
	M_DCOF      =  99, // dc-offset
	M_DDMD      = 100, // ddm
	M_DEEM      = 101, // de-emphasis
	M_DELA      = 102, // delay
	M_DEST      = 103, // destination
	M_DEWP      = 104, // dewpoint
	M_DFBA      = 105, // diff-boresight-angle
	M_DIFR      = 106, // differentiate
	M_DIFT      = 107, // differential-temp
	M_DIGS      = 108, // dig-spec
	M_DISP      = 109, // display
	M_DIST      = 110, // distance
	M_DIVG      = 111, // divergence
	M_DIVS      = 112, // divisions
	M_DMDS      = 113, // dominant-mod-sig
	M_DPFR      = 114, // doppler-freq
	M_DPSH      = 115, // doppler-shift
	M_DROO      = 116, // droop
	M_DSFC      = 117, // diss-factor
	M_DSTR      = 118, // distance-r
	M_DSTX      = 119, // distance-x
	M_DSTY      = 120, // distance-y
	M_DSTZ      = 121, // distance-z
	M_DTER      = 122, // diff-temp-error
	M_DTIL      = 123, // diff-temp-interval
	M_DTMD      = 124, // do-timed-digital
	M_DTOR      = 125, // distortion
	M_DTSP      = 126, // diff-temp-stop
	M_DTST      = 127, // diff-temp-start
	M_DUTY      = 128, // duty-cycle
	M_DVPN      = 129, // dev-pneg
	M_DVPP      = 130, // dev-ppos
	M_DWBT      = 131, // data-word-bit
	M_DYRA      = 132, // dynamic-range
	M_EFCY      = 133, // efficacy
	M_EFFI      = 134, // eff
	M_EINM      = 135, // event-interval
	M_ERRI      = 136, // error-index
	M_ERRO      = 137, // error
	M_EVAO      = 138, // event-after-occurrences
	M_EVDL      = 139, // event-delay
	M_EVEO      = 140, // event-each-occurrence
	M_EVEV      = 141, // event-every
	M_EVFO      = 142, // event-first-occurrence
	M_EVGB      = 143, // event-gated-by
	M_EVGF      = 144, // event-gate-from
	M_EVGR      = 145, // event-gate-forever
	M_EVGT      = 146, // event-gate-to
	M_EVOU      = 147, // event-out
	M_EVSB      = 148, // event-sync-bit
	M_EVSF      = 149, // event-sync-freq
	M_EVSL      = 150, // event-slope
	M_EVSW      = 151, // event-sync-word
	M_EVTF      = 152, // event-time-from
	M_EVTI      = 153, // event-indicator
	M_EVTR      = 154, // event-time-forever
	M_EVTT      = 155, // event-time-to
	M_EVUN      = 156, // event-until
	M_EVWH      = 157, // event-when
	M_EVXE      = 158, // event-sense
	M_EVXM      = 159, // event-stim
	M_EXAE      = 160, // except at every
	M_EXNM      = 161, // exchange-number
	M_EXPO      = 162, // exponent
	M_FALL      = 163, // fall-time
	M_FCLN      = 164, // focal-length
	M_FDST      = 165, // field-strength
	M_FIAL      = 166, // first-active-line
	M_FILT      = 167, // filter
	M_FLTC      = 168, // fault-count
	M_FLTS      = 169, // fault-test
	M_FLUT      = 170, // fluid-type
	M_FMCP      = 171, // fm-comp
	M_FMCU      = 172, // fm-coupl
	M_FMFQ      = 173, // fm-freq
	M_FMSR      = 174, // fm-source
	M_FRCE      = 175, // force
	M_FRCR      = 176, // force-rate
	M_FREQ      = 177, // freq
	M_FRMT      = 178, // format
	M_FRQ0      = 179, // freq-zero
	M_FRQ1      = 180, // freq-one
	M_FRQD      = 181, // freq-dev
	M_FRQP      = 182, // freq-pairing
	M_FRQQ      = 183, // freq-quies
	M_FRQR      = 184, // freq-ratio
	M_FRQW      = 185, // freq-window
	M_FUEL      = 186, // fuel-supply
	M_FXDN      = 187, // flux-dens
	M_FXIP      = 188, // flux-dens-in-phase
	M_FXQD      = 189, // flux-dens-quad
	M_GSLP      = 190, // glide-slope
	M_GSRE      = 191, // gray-scale-resolution
	M_HAPW      = 192, // harm-power
	M_HARM      = 193, // harmonics
	M_HARN      = 194, // harm-number
	M_HARP      = 195, // harm-phase
	M_HARV      = 196, // harm-voltage
	M_HFOV      = 197, // h-field-of-view
	M_HIZZ      = 198, // hiz
	M_HLAE      = 199, // h-los-align-error
	M_HMDF      = 200, // hi-mod-freq
	M_HTAG      = 201, // h-target-angle
	M_HTOF      = 202, // h-target-offset
	M_HUMY      = 203, // humidity
	M_IASP      = 204, // ias
	M_ICWB      = 205, // invalid-command-word-bit
	M_IDSE      = 206, // ident-sig-ep
	M_IDSF      = 207, // ident-sig-freq
	M_IDSG      = 208, // ident-sig
	M_IDSM      = 209, // ident-sig-mod
	M_IDWB      = 210, // invalid-data-word-bit
	M_IJIT      = 211, // int-jitter
	M_ILLU      = 212, // illum
	M_INDU      = 213, // ind
	M_INTG      = 214, // integrate
	M_INTL      = 215, // interval
	M_IRAT      = 216, // int-rate
	M_ISTI      = 217, // illegal-state-indicator
	M_ISWB      = 218, // invalid-status-word-bit
	M_ITER      = 219, // iterate
	M_ITRO      = 220, // intensity-ratio
	M_IVCW      = 221, // invalid-command-word
	M_IVDL      = 222, // invalid-data-word-length
	M_IVDP      = 223, // invalid-data-word-parity
	M_IVDS      = 224, // invalid-data-word-sync
	M_IVDT      = 225, // invalid-data-word-tr
	M_IVDW      = 226, // invalid-data-word
	M_IVMG      = 227, // invalid-message-gap
	M_IVOA      = 228, // invalid-one-amplitude
	M_IVRT      = 229, // invalid-response-time
	M_IVSW      = 230, // invalid-status-word
	M_IVWC      = 231, // invalid-word-count
	M_IVWG      = 232, // invalid-word-gap
	M_IVWL      = 233, // invalid-word-length
	M_IVZA      = 234, // invalid-zero-amplitude
	M_IVZC      = 235, // invalid-zero-crossing
	M_LDFM      = 236, // load-from
	M_LDTO      = 237, // load-to
	M_LDVW      = 238, // load-wave
	M_LIPF      = 239, // lines-per-channel
	M_LMDF      = 240, // lo-mod-freq
	M_LMIN      = 241, // lum-int
	M_LOCL      = 242, // localizer
	M_LSAE      = 243, // los-align-error
	M_LUMF      = 244, // lum-flux
	M_LUMI      = 245, // luminance
	M_LUMT      = 246, // lum-temp
	M_MAGB      = 247, // mag-bearing
	M_MAGR      = 248, // mag-bearing-rate
	M_MAMP      = 249, // mod-ampl
	M_MANI      = 250, // manual-intervention
	M_MASF      = 251, // mass-flow
	M_MASK      = 252, // mask-one
	M_MATH      = 253, // math
	M_MAXT      = 254, // max-time
	M_MBAT      = 255, // main-beam-atten
	M_MDPN      = 256, // mod-pneg
	M_MDPP      = 257, // mod-ppos
	M_MDSC      = 258, // mod-source
	M_MGAP      = 259, // message-gap
	M_MMOD      = 260, // mean-mod
	M_MODD      = 261, // mod-dist
	M_MODE      = 262, // mode
	M_MODF      = 263, // mod-freq
	M_MODO      = 264, // mod-offset
	M_MODP      = 265, // mod-phase
	M_MPFM      = 266, // multp-from
	M_MPTO      = 267, // multp-to
	M_MRCO      = 268, // min-resolv-contrast
	M_MRKB      = 269, // marker-beacon
	M_MRTD      = 270, // min-resolv-temp-diff
	M_MSKZ      = 271, // mask-zero
	M_MSNR      = 272, // minimum-sense-rate
	M_MTFD      = 273, // mtf-direction
	M_MTFP      = 274, // mtf-freq-points
	M_MTFU      = 275, // modulation-transfer-function
	M_NEDT      = 276, // noise-eq-diff-temp
	M_NEGS      = 277, // neg-slope
	M_NHAR      = 278, // non-harmonics
	M_NLIN      = 279, // non-lin
	M_NOAD      = 280, // noise-ampl-dens
	M_NOAV      = 281, // noise-av
	M_NOIS      = 282, // noise
	M_NOPD      = 283, // noise-pwr-dens
	M_NOPK      = 284, // noise-p
	M_NOPP      = 285, // noise-pp
	M_NOTR      = 286, // noise-trms
	M_NPWT      = 287, // neg-pulse-width
	M_OAMP      = 288, // one-amplitude
	M_OTMP      = 289, // oper-temp
	M_OVER      = 290, // overshoot
	M_P3DV      = 291, // p3-dev
	M_P3LV      = 292, // p3-level
	M_PAMP      = 293, // p-ampl
	M_PANG      = 294, // phase-angle
	M_PARE      = 295, // parity-even
	M_PARO      = 296, // parity-odd
	M_PAST      = 297, // pulse-ampl-stab
	M_PATH      = 298, // path
	M_PATN      = 299, // pulse-atten
	M_PCCU      = 300, // pac-coupl
	M_PCLS      = 301, // pulse-class
	M_PCSR      = 302, // pac-source
	M_PDEV      = 303, // phase-dev
	M_PDGN      = 304, // peak-degen
	M_PDRP      = 305, // pair-droop
	M_PERI      = 306, // period
	M_PEST      = 307, // pulse-energy-stab
	M_PHPN      = 308, // phase-pneg
	M_PHPP      = 309, // phase-ppos
	M_PJIT      = 310, // phase-jit
	M_PKDV      = 311, // peak-dev
	M_PLAN      = 312, // pla
	M_PLAR      = 313, // pla-rate
	M_PLEG      = 314, // pulse-energy
	M_PLID      = 315, // pulse-ident
	M_PLSE      = 316, // pulses-excl
	M_PLSI      = 317, // pulses-incl
	M_PLWD      = 318, // pulse-width
	M_PMCU      = 319, // pm-coupl
	M_PMFQ      = 320, // pm-freq
	M_PMSR      = 321, // pm-source
	M_PODN      = 322, // power-dens
	M_POSI      = 323, // position
	M_POSS      = 324, // pos-slope
	M_POWA      = 325, // power-av
	M_POWP      = 326, // power-p
	M_POWR      = 327, // power
	M_PPOS      = 328, // pulse-posn
	M_PPST      = 329, // pulse-period-stab
	M_PPWT      = 330, // pos-pulse-width
	M_PRCD      = 331, // proceed
	M_PRDF      = 332, // power-diff
	M_PRFR      = 333, // prf
	M_PRIO      = 334, // priority
	M_PROA      = 335, // press-osc-ampl
	M_PROF      = 336, // press-osc-freq
	M_PRSA      = 337, // press-a
	M_PRSG      = 338, // press-g
	M_PRSR      = 339, // press-rate
	M_PSHI      = 340, // phase-shift
	M_PSHT      = 341, // preshoot
	M_PSPC      = 342, // pair-spacing
	M_PSPE      = 343, // pulse-spect
	M_PSPT      = 344, // pulse-spect-threshold
	M_PWRL      = 345, // pwr-lmt
	M_QFAC      = 346, // q
	M_QUAD      = 347, // quad
	M_RADL      = 348, // radial
	M_RADR      = 349, // radial-rate
	M_RAIL      = 350, // radiance-interval
	M_RASP      = 351, // radiance-stop
	M_RAST      = 352, // radiance-start
	M_RCVS      = 353, // receiver-sensitivity
	M_RDNC      = 354, // radiance
	M_REAC      = 355, // reactance
	M_REFF      = 356, // ref-freq
	M_REFI      = 357, // ref-inertial
	M_REFP      = 358, // ref-power
	M_REFR      = 359, // ref-res
	M_REFU      = 360, // ref-uut
	M_REFV      = 361, // ref-volt
	M_REFX      = 362, // ref
	M_RELB      = 363, // rel-bearing
	M_RELH      = 364, // relative-humidity
	M_RELW      = 365, // relative-wind
	M_REPT      = 366, // repeat
	M_RERR      = 367, // range-error
	M_RESB      = 368, // resolution-bandwidth
	M_RESI      = 369, // res
	M_RESP      = 370, // resp
	M_RESR      = 371, // res-ratio
	M_RING      = 372, // ringing
	M_RISE      = 373, // rise-time
	M_RLBR      = 374, // rel-bearing-rate
	M_RMNS      = 375, // ramp-neg-slope
	M_RMPS      = 376, // ramp-pos-slope
	M_ROUN      = 377, // rounding
	M_RPDV      = 378, // range-pulse-dev
	M_RPEC      = 379, // range-pulse-echo
	M_RPHF      = 380, // ref-phase-freq
	M_RPLD      = 381, // ref-pulses-dev
	M_RPLE      = 382, // reply-eff
	M_RPLI      = 383, // ref-pulses-incl
	M_RPLX      = 384, // ref-pulses-excl
	M_RSPH      = 385, // resp-hiz
	M_RSPO      = 386, // resp-one
	M_RSPT      = 387, // response-time
	M_RSPZ      = 388, // resp-zero
	M_RTRS      = 389, // rotor-speed
	M_SASP      = 390, // sample-spacing
	M_SATM      = 391, // sample-time
	M_SBAT      = 392, // satellite-beam-atten
	M_SBCF      = 393, // sub-car-freq
	M_SBCM      = 394, // sub-car-mod
	M_SBEV      = 395, // strobe-to-event
	M_SBFM      = 396, // subtract-from
	M_SBTO      = 397, // subtract-to
	M_SCNT      = 398, // sample-count
	M_SDEL      = 399, // sense-delay
	M_SERL      = 400, // serial-lsb-first
	M_SERM      = 401, // serial-msb-first
	M_SETT      = 402, // settle-time
	M_SGNO      = 403, // sig-noise
	M_SHFS      = 404, // shaft-speed
	M_SIMU      = 405, // do-simultaneous
	M_SKEW      = 406, // skew-time
	M_SLEW      = 407, // slew-rate
	M_SLRA      = 408, // slant-range-accel
	M_SLRG      = 409, // slant-range
	M_SLRR      = 410, // slant-range-rate
	M_SLSD      = 411, // sls-dev
	M_SLSL      = 412, // sls-level
	M_SMAV      = 413, // sample-av
	M_SMPL      = 414, // sample
	M_SMPW      = 415, // sample-width
	M_SMTH      = 416, // smooth
	M_SNAD      = 417, // sinad
	M_SNSR      = 418, // sense-rate
	M_SPCG      = 419, // spacing
	M_SPED      = 420, // speed
	M_SPGR      = 421, // spec-grav
	M_SPTM      = 422, // spec-temp
	M_SQD1      = 423, // sqtr-dist-1
	M_SQD2      = 424, // sqtr-dist-2
	M_SQD3      = 425, // sqtr-dist-3
	M_SQTD      = 426, // sqtr-dist
	M_SQTR      = 427, // sqtr-rate
	M_STAT      = 428, // status
	M_STBM      = 429, // satellite-beam
	M_STIM      = 430, // stim
	M_STMH      = 431, // stim-hiz
	M_STMO      = 432, // stim-one
	M_STMP      = 433, // static-temp
	M_STMR      = 434, // stim-rate
	M_STMZ      = 435, // stim-zero
	M_STOP      = 436, // stop
	M_STPA      = 437, // static-press-a
	M_STPG      = 438, // static-press-g
	M_STPR      = 439, // static-press-rate
	M_STRD      = 440, // standard
	M_STRT      = 441, // start
	M_STWD      = 442, // status-word
	M_SUSP      = 443, // susceptance
	M_SVCP      = 444, // save-comp
	M_SVFM      = 445, // save-from
	M_SVTO      = 446, // save-to
	M_SVWV      = 447, // save-wave
	M_SWBT      = 448, // status-word-bit
	M_SWPT      = 449, // sweep-time
	M_SWRA      = 450, // swr
	M_SYDL      = 451, // sync-delay
	M_SYNC      = 452, // sync
	M_TASP      = 453, // tas
	M_TASY      = 454, // time-asym
	M_TCAP      = 455, // temp-coeff-cap
	M_TCBT      = 456, // tgt-coordinate-bottom
	M_TCLT      = 457, // tgt-coordinate-left
	M_TCRT      = 458, // tgt-coordinate-right
	M_TCTP      = 459, // tgt-coordinate-top
	M_TCUR      = 460, // temp-coeff-current
	M_TDAT      = 461, // target-data
	M_TEMP      = 462, // temp
	M_TEQL      = 463, // test-equip-listener
	M_TEQT      = 464, // test-equip-talker
	M_TGMD      = 465, // trigger-mode
	M_TGTA      = 466, // target-range-accel
	M_TGTD      = 467, // target-range
	M_TGTP      = 468, // target-type
	M_TGTR      = 469, // target-range-rate
	M_TGTS      = 470, // last-pulse-range
	M_THRT      = 471, // thrust
	M_TIEV      = 472, // time-every
	M_TILT      = 473, // tilt
	M_TIME      = 474, // time
	M_TIMP      = 475, // test-equip-imp
	M_TIND      = 476, // temp-coeff-ind
	M_TIUN      = 477, // time-until
	M_TIWH      = 478, // time-when
	M_TJIT      = 479, // time-jit
	M_TMON      = 480, // test-equip-monitor
	M_TOPA      = 481, // total-press-a
	M_TOPG      = 482, // total-press-g
	M_TOPR      = 483, // total-press-rate
	M_TORQ      = 484, // torque
	M_TPHD      = 485, // three-phase-delta
	M_TPHY      = 486, // three-phase-wye
	M_TREA      = 487, // temp-coeff-react
	M_TRES      = 488, // temp-coeff-res
	M_TRGS      = 489, // trig-source
	M_TRIG      = 490, // trig
	M_TRLV      = 491, // trig-level
	M_TRN0      = 492, // trans-zero
	M_TRN1      = 493, // trans-one
	M_TRNP      = 494, // trans-period
	M_TRNS      = 495, // trans-sync
	M_TROL      = 496, // test-equip-role
	M_TRSL      = 497, // trig-slope
	M_TRUE      = 498, // true
	M_TRUN      = 499, // timer-until
	M_TRWH      = 500, // timer-when
	M_TSIM      = 501, // test-equip-simulate
	M_TSPC      = 502, // test-point-count
	M_TTMP      = 503, // total-temp
	M_TVOL      = 504, // temp-coeff-volt
	M_TYPE      = 505, // type
	M_UNDR      = 506, // undershoot
	M_UNFY      = 507, // uniformity
	M_UUTL      = 508, // uut-listener
	M_UUTT      = 509, // uut-talker
	M_VALU      = 510, // value
	M_VBAC      = 511, // vibration-accel
	M_VBAN      = 512, // video-bandwidth
	M_VBAP      = 513, // vibration-ampl-p
	M_VBPP      = 514, // vibration-ampl-pp
	M_VBRT      = 515, // vibration-rate
	M_VBTR      = 516, // vibration-ampl-trms
	M_VDIV      = 517, // volt-per-div
	M_VEAO      = 518, // event-after-occurrences-value
	M_VEDL      = 519, // event-delay-value
	M_VEEO      = 520, // event-each-occurrence-value
	M_VEFO      = 521, // event-first-occurrence-value
	M_VEGF      = 522, // event-gate-for
	M_VETF      = 523, // event-time-for
	M_VFOV      = 524, // v-field-of-view
	M_VINS      = 525, // voltage-inst
	M_VLAE      = 526, // v-los-align-error
	M_VLAV      = 527, // av-voltage
	M_VLPK      = 528, // voltage-p
	M_VLPP      = 529, // voltage-pp
	M_VLT0      = 530, // voltage-zero
	M_VLT1      = 531, // voltage-one
	M_VLTL      = 532, // volt-lmt
	M_VLTQ      = 533, // voltage-quies
	M_VLTR      = 534, // voltage-ramped
	M_VLTS      = 535, // voltage-stepped
	M_VOLF      = 536, // volume-flow
	M_VOLR      = 537, // voltage-ratio
	M_VOLT      = 538, // voltage
	M_VPHF      = 539, // var-phase-freq
	M_VPHM      = 540, // var-phase-mod
	M_VPKN      = 541, // voltage-p-neg
	M_VPKP      = 542, // voltage-p-pos
	M_VRMS      = 543, // voltage-trms
	M_VTAG      = 544, // v-target-angle
	M_VTOF      = 545, // v-target-offset
	M_WAIT      = 546, // wait
	M_WAVE      = 547, // wave-length
	M_WDLN      = 548, // word-length
	M_WDRT      = 549, // word-rate
	M_WGAP      = 550, // word-gap
	M_WILD      = 551, // wild
	M_WIND      = 552, // wind-speed
	M_WRDC      = 553, // word-count
	M_WTRN      = 554, // word-transition
	M_XACE      = 555, // x-autocollimation-error
	M_XBAG      = 556, // x-boresight-angle
	M_YACE      = 557, // y-autocollimation-error
	M_YBAG      = 558, // y-boresight-angle
	M_ZAMP      = 559, // zero-amplitude
	M_ZCRS      = 560, // zero-crossing
	M_ZERO      = 561, // zero-index
	M__CNT      = 562, // symbol count
};
//
//	MODULETYPES
//
enum enumTyxModuletypes {
	T_ACS       =   1, // name not available
	T_API       =   2, // name not available
	T_ARB       =   3, // name not available
	T_ASA       =   4, // name not available
	T_DCS       =   5, // name not available
	T_DIG       =   6, // name not available
	T_DMM       =   7, // name not available
	T_DWG       =   8, // name not available
	T_FNG       =   9, // name not available
	T_FTM       =  10, // name not available
	T_MBT       =  11, // name not available
	T_MFU       =  12, // name not available
	T_MTR       =  13, // name not available
	T_PAT       =  14, // name not available
	T_PCM       =  15, // name not available
	T_PLG       =  16, // name not available
	T_PSS       =  17, // name not available
	T_PWM       =  18, // name not available
	T_QAL       =  19, // name not available
	T_RSV       =  20, // name not available
	T_RSY       =  21, // name not available
	T_SNG       =  22, // name not available
	T_SRS       =  23, // name not available
	T_VDG       =  24, // name not available
	T__CNT      =  25, // symbol count
};
//
//	DIMS-A
//
enum enumTyxDimsA {
	D_1553A     =   1, // mil-1553a
	D_1553B     =   2, // mil-1553b
	D_ALLLS     =   3, // all-listener
	D_AMI       =   4, // ami
	D_AR429     =   5, // arinc-429
	D_ARDC      =   6, // ardc
	D_BIP       =   7, // bip
	D_CONMD     =   8, // con-mode
	D_CONRT     =   9, // con-rt
	D_CSM       =  10, // csm
	D_CSN       =  11, // csn
	D_CSOC      =  12, // consecutive-occurrences
	D_HDB       =  13, // hdb
	D_ICAN      =  14, // ican
	D_ICAO      =  15, // icao
	D_IEEE488   =  16, // ieee-488
	D_LNGTH     =  17, // length
	D_MASTR     =  18, // master
	D_MIP       =  19, // mip
	D_MONTR     =  20, // monitor
	D_NRZ       =  21, // nrz
	D_OFF       =  22, // off
	D_ON        =  23, // on
	D_PARA      =  24, // parallel
	D_PRIM      =  25, // primary
	D_PRTY      =  26, // parity
	D_REDT      =  27, // redundant
	D_RS232     =  28, // rs-232
	D_RS422     =  29, // rs-422
	D_RTCON     =  30, // rt-con
	D_RTRT      =  31, // rt-rt
	D_RZ        =  32, // rz
	D_SERL      =  33, // serial-lsb-first
	D_SERM      =  34, // serial-msb-first
	D_SLAVE     =  35, // slave
	D_SYNC      =  36, // sync
	D_TLKLS     =  37, // talker-listener
	D_TR        =  38, // t-r
	D_WADC      =  39, // wadc
	D__CNT      =  40, // symbol count
};
//
//	DIMS-B
//
enum enumTyxDimsB {
	R__CNT      =   1, // symbol count
};
#endif // _LEXKEY_H_
