#ifndef _LEXKEY_H_
#define _LEXKEY_H_
//
//	VERBS
//
enum enumTyxVerbs {
	V_APP       =   1, // apply
	V_ARM       =   2, // arm
	V_CAL       =   3, // calculate
	V_CHN       =   4, // change
	V_CLS       =   5, // close
	V_CMP       =   6, // compare
	V_CON       =   7, // connect
	V_CPL       =   8, // couple
	V_CRE       =   9, // create
	V_DCL       =  10, // declare
	V_DEF       =  11, // define
	V_DEL       =  12, // delete
	V_DIS       =  13, // disconnect
	V_DO        =  14, // do
	V_DSB       =  15, // disable
	V_ELS       =  16, // else
	V_ENB       =  17, // enable
	V_END       =  18, // end
	V_EST       =  19, // establish
	V_FIN       =  20, // finish
	V_FOR       =  21, // for
	V_FTH       =  22, // fetch
	V_GTO       =  23, // go to
	V_IDY       =  24, // identify
	V_IF        =  25, // if
	V_INC       =  26, // include
	V_INP       =  27, // input
	V_INX       =  28, // initiate
	V_LVE       =  29, // leave
	V_MEA       =  30, // measure
	V_MON       =  31, // monitor
	V_OPN       =  32, // open
	V_OUT       =  33, // output
	V_PFM       =  34, // perform
	V_PRV       =  35, // prove
	V_RD        =  36, // read
	V_REM       =  37, // remove
	V_REQ       =  38, // require
	V_RES       =  39, // resume
	V_RST       =  40, // reset
	V_SET       =  41, // setup
	V_SNS       =  42, // sense
	V_STI       =  43, // stimulate
	V_TRM       =  44, // terminate
	V_UCP       =  45, // uncouple
	V_UPD       =  46, // update
	V_VER       =  47, // verify
	V_WHL       =  48, // while
	V_WTF       =  49, // wait for
	V_XTN       =  50, // extend
	V__CNT      =  51, // symbol count
};
//
//	NOUNS
//
enum enumTyxNouns {
	N_ACS       =   1, // ac signal
	N_ADF       =   2, // adf
	N_AMB       =   3, // ambient conditions
	N_AMS       =   4, // am signal
	N_ATC       =   5, // atc
	N_BUS       =   6, // bus protocol
	N_BUT       =   7, // button
	N_CLX       =   8, // complex signal
	N_COM       =   9, // common
	N_DCF       =  10, // digital configuration
	N_DCS       =  11, // dc signal
	N_DGT       =  12, // digital test
	N_DIS       =  13, // displacement
	N_DME       =  14, // dme
	N_DOP       =  15, // doppler
	N_EAR       =  16, // earth
	N_EMF       =  17, // em field
	N_EPW       =  18, // exponential pulse wave
	N_EVS       =  19, // events
	N_EVT       =  20, // event
	N_EXC       =  21, // exchange
	N_FLU       =  22, // fluid signal
	N_FMS       =  23, // fm signal
	N_HEA       =  24, // heat
	N_IFF       =  25, // iff
	N_ILS       =  26, // ils
	N_IMP       =  27, // impedance
	N_INF       =  28, // infrared
	N_LAS       =  29, // laser
	N_LCL       =  30, // logic control
	N_LDT       =  31, // logic data
	N_LGT       =  32, // light
	N_LLD       =  33, // logic load
	N_LRF       =  34, // logic reference
	N_LTR       =  35, // laser target return
	N_MAN       =  36, // manometric
	N_MDS       =  37, // modulated signal
	N_MIF       =  38, // multi-sensor-infrared
	N_MIL       =  39, // multi-sensor-light
	N_PAC       =  40, // pulsed ac
	N_PAM       =  41, // pam
	N_PAT       =  42, // pulsed ac train
	N_PDC       =  43, // pulsed dc
	N_PDP       =  44, // pulsed doppler
	N_PDT       =  45, // pulsed dc train
	N_PMS       =  46, // pm signal
	N_RDN       =  47, // random noise
	N_RDS       =  48, // radar signal
	N_RPS       =  49, // ramp signal
	N_RSL       =  50, // resolver
	N_RTN       =  51, // rotation
	N_SCS       =  52, // sup car signal
	N_SHT       =  53, // short
	N_SIM       =  54, // simultaneous
	N_SIN       =  55, // sinc wave
	N_SQW       =  56, // square wave
	N_STM       =  57, // stepper motor
	N_STS       =  58, // step signal
	N_SYN       =  59, // synchro
	N_TAC       =  60, // tacan
	N_TDG       =  61, // timed digital
	N_TED       =  62, // turbine engine data
	N_TMI       =  63, // time interval
	N_TMR       =  64, // timer
	N_TRI       =  65, // triangular wave signal
	N_VBR       =  66, // vibration
	N_VID       =  67, // video signal
	N_VOR       =  68, // vor
	N_WAV       =  69, // waveform
	N__CNT      =  70, // symbol count
};
//
//	MODIFIERS
//
enum enumTyxModifiers {
	M_ACCD      =   1, // acceptance-code
	M_ACCF      =   2, // ac-comp-freq
	M_ACCP      =   3, // ac-comp
	M_ACMK      =   4, // acceptance-mask
	M_ADFM      =   5, // add-from
	M_ADLN      =   6, // addr-lines
	M_ADRG      =   7, // address-reg
	M_ADTO      =   8, // add-to
	M_AGER      =   9, // age-rate
	M_ALLW      =  10, // allowance
	M_ALTI      =  11, // alt
	M_ALTR      =  12, // alt-rate
	M_AMBT      =  13, // ambient-temp
	M_AMCP      =  14, // am-comp
	M_AMCU      =  15, // am-coupl
	M_AMFQ      =  16, // am-freq
	M_AMMC      =  17, // ampl-mod-c
	M_AMMF      =  18, // ampl-mod-f
	M_AMPL      =  19, // ampl-mod
	M_AMSH      =  20, // am-shift
	M_AMSR      =  21, // am-source
	M_ANAC      =  22, // angle-accel
	M_ANAX      =  23, // angle-accel-x
	M_ANAY      =  24, // angle-accel-y
	M_ANAZ      =  25, // angle-accel-z
	M_ANGL      =  26, // angle
	M_ANGP      =  27, // angle-phi
	M_ANGT      =  28, // angle-theta
	M_ANGX      =  29, // angle-x
	M_ANGY      =  30, // angle-y
	M_ANGZ      =  31, // angle-z
	M_ANRT      =  32, // angle-rate
	M_ANRX      =  33, // angle-rate-x
	M_ANRY      =  34, // angle-rate-y
	M_ANRZ      =  35, // angle-rate-z
	M_ANSD      =  36, // ant-speed-dev
	M_ATMS      =  37, // atmos
	M_ATTE      =  38, // attenuation
	M_ATTN      =  39, // atten
	M_AUCO      =  40, // autocollimation-error
	M_BAND      =  41, // bandwidth
	M_BARP      =  42, // barometric-press
	M_BDTH      =  43, // beam-detection-threshold
	M_BITP      =  44, // bit-period
	M_BITR      =  45, // bit-rate
	M_BKPH      =  46, // back-porch
	M_BLKT      =  47, // blackbody-temp
	M_BRAN      =  48, // boresight-angle
	M_BSTO      =  49, // bus-timeout
	M_BSVT      =  50, // base-vector
	M_BTRN      =  51, // bit-transition
	M_BURD      =  52, // burst-droop
	M_BURR      =  53, // burst-rep-rate
	M_BURS      =  54, // burst
	M_BUSM      =  55, // bus-mode
	M_BUSS      =  56, // bus-spec
	M_CAMG      =  57, // camera-gain
	M_CAMP      =  58, // car-ampl
	M_CAPA      =  59, // cap
	M_CCOM      =  60, // count-command
	M_CDAT      =  61, // count-data
	M_CFRQ      =  62, // car-freq
	M_CHAN      =  63, // channel
	M_CHID      =  64, // channel-ident
	M_CHIT      =  65, // chan-integrity
	M_CHRM      =  66, // car-harmonics
	M_CLKS      =  67, // clock-source
	M_CMCH      =  68, // compare-ch
	M_CMDW      =  69, // command-word
	M_CMPL      =  70, // compl
	M_CMTO      =  71, // compare-to
	M_CMWB      =  72, // command-word-bit
	M_CMWV      =  73, // compare-wave
	M_COMD      =  74, // command
	M_COND      =  75, // conductance
	M_COUN      =  76, // count
	M_CPHS      =  77, // car-phase
	M_CPKN      =  78, // current-p-neg
	M_CPKP      =  79, // current-p-pos
	M_CPLG      =  80, // coupling
	M_CRSD      =  81, // car-resid
	M_CRSF      =  82, // crest-factor
	M_CSTS      =  83, // count-status
	M_CTRQ      =  84, // cutoff-freq
	M_CUPK      =  85, // current-p
	M_CUPP      =  86, // current-pp
	M_CUR0      =  87, // current-zero
	M_CUR1      =  88, // current-one
	M_CURA      =  89, // av-current
	M_CURI      =  90, // current-inst
	M_CURL      =  91, // current-lmt
	M_CURQ      =  92, // current-quies
	M_CURR      =  93, // current
	M_CURT      =  94, // current-trms
	M_CWLV      =  95, // cw-level
	M_DATA      =  96, // data
	M_DATL      =  97, // data-word-length
	M_DATP      =  98, // data-word-parity
	M_DATS      =  99, // data-word-sync
	M_DATT      = 100, // data-word-tr
	M_DATW      = 101, // data-word
	M_DBLI      = 102, // dbl-int
	M_DBND      = 103, // doppler-bandwidth
	M_DBRC      = 104, // debris-count
	M_DBRS      = 105, // debris-size
	M_DCOF      = 106, // dc-offset
	M_DDMD      = 107, // ddm
	M_DEEM      = 108, // de-emphasis
	M_DELA      = 109, // delay
	M_DEST      = 110, // destination
	M_DEWP      = 111, // dewpoint
	M_DFBA      = 112, // diff-boresight-angle
	M_DIFR      = 113, // differentiate
	M_DIFT      = 114, // differential-temp
	M_DIGS      = 115, // dig-spec
	M_DISP      = 116, // display
	M_DIST      = 117, // distance
	M_DIVG      = 118, // divergence
	M_DIVS      = 119, // divisions
	M_DMDS      = 120, // dominant-mod-sig
	M_DPFR      = 121, // doppler-freq
	M_DPSH      = 122, // doppler-shift
	M_DROO      = 123, // droop
	M_DSFC      = 124, // diss-factor
	M_DSPC      = 125, // dist-pos-count
	M_DSTP      = 126, // distortion-positions
	M_DSTR      = 127, // distance-r
	M_DSTX      = 128, // distance-x
	M_DSTY      = 129, // distance-y
	M_DSTZ      = 130, // distance-z
	M_DTCT      = 131, // detector-count
	M_DTER      = 132, // diff-temp-error
	M_DTIL      = 133, // diff-temp-interval
	M_DTMD      = 134, // do-timed-digital
	M_DTOR      = 135, // distortion
	M_DTSC      = 136, // detector-scan
	M_DTSP      = 137, // diff-temp-stop
	M_DTST      = 138, // diff-temp-start
	M_DUTY      = 139, // duty-cycle
	M_DVPN      = 140, // dev-pneg
	M_DVPP      = 141, // dev-ppos
	M_DWBT      = 142, // data-word-bit
	M_DYRA      = 143, // dynamic-range
	M_EDLN      = 144, // end-line
	M_EDUT      = 145, // end-unit
	M_EFCY      = 146, // efficacy
	M_EFFI      = 147, // eff
	M_EGDR      = 148, // energy-distribution
	M_EINM      = 149, // event-interval
	M_ERRI      = 150, // error-index
	M_ERRO      = 151, // error
	M_EVAO      = 152, // event-after-occurrences
	M_EVDL      = 153, // event-delay
	M_EVEO      = 154, // event-each-occurrence
	M_EVEV      = 155, // event-every
	M_EVFO      = 156, // event-first-occurrence
	M_EVGB      = 157, // event-gated-by
	M_EVGF      = 158, // event-gate-from
	M_EVGR      = 159, // event-gate-forever
	M_EVGT      = 160, // event-gate-to
	M_EVOU      = 161, // event-out
	M_EVSB      = 162, // event-sync-bit
	M_EVSF      = 163, // event-sync-freq
	M_EVSL      = 164, // event-slope
	M_EVSW      = 165, // event-sync-word
	M_EVTF      = 166, // event-time-from
	M_EVTI      = 167, // event-indicator
	M_EVTR      = 168, // event-time-forever
	M_EVTT      = 169, // event-time-to
	M_EVUN      = 170, // event-until
	M_EVWH      = 171, // event-when
	M_EVXE      = 172, // event-sense
	M_EVXM      = 173, // event-stim
	M_EXAE      = 174, // except at every
	M_EXNM      = 175, // exchange-number
	M_EXPO      = 176, // exponent
	M_FALL      = 177, // fall-time
	M_FCLN      = 178, // focal-length
	M_FCNT      = 179, // frame-count
	M_FDST      = 180, // field-strength
	M_FDVW      = 181, // field-of-view
	M_FIAL      = 182, // first-active-line
	M_FILT      = 183, // filter
	M_FLTC      = 184, // fault-count
	M_FLTS      = 185, // fault-test
	M_FLUT      = 186, // fluid-type
	M_FMCP      = 187, // fm-comp
	M_FMCU      = 188, // fm-coupl
	M_FMFQ      = 189, // fm-freq
	M_FMSR      = 190, // fm-source
	M_FORW      = 191, // four-wire
	M_FRCE      = 192, // force
	M_FRCR      = 193, // force-rate
	M_FREQ      = 194, // freq
	M_FRMT      = 195, // format
	M_FRQ0      = 196, // freq-zero
	M_FRQ1      = 197, // freq-one
	M_FRQD      = 198, // freq-dev
	M_FRQP      = 199, // freq-pairing
	M_FRQQ      = 200, // freq-quies
	M_FRQR      = 201, // freq-ratio
	M_FRQW      = 202, // freq-window
	M_FRSP      = 203, // freq-span
	M_FUEL      = 204, // fuel-supply
	M_FXDN      = 205, // flux-dens
	M_FXIP      = 206, // flux-dens-in-phase
	M_FXQD      = 207, // flux-dens-quad
	M_GAMA      = 208, // gamma
	M_GSLP      = 209, // glide-slope
	M_GSRE      = 210, // gray-scale-resolution
	M_HAPW      = 211, // harm-power
	M_HARM      = 212, // harmonics
	M_HARN      = 213, // harm-number
	M_HARP      = 214, // harm-phase
	M_HARV      = 215, // harm-voltage
	M_HFOV      = 216, // h-field-of-view
	M_HIZZ      = 217, // hiz
	M_HLAE      = 218, // h-los-align-error
	M_HMDF      = 219, // hi-mod-freq
	M_HP01      = 220, // harm-1-power
	M_HP02      = 221, // harm-2-power
	M_HP03      = 222, // harm-3-power
	M_HP04      = 223, // harm-4-power
	M_HP05      = 224, // harm-5-power
	M_HP06      = 225, // harm-6-power
	M_HP07      = 226, // harm-7-power
	M_HP08      = 227, // harm-8-power
	M_HP09      = 228, // harm-9-power
	M_HP10      = 229, // harm-10-power
	M_HP11      = 230, // harm-11-power
	M_HP12      = 231, // harm-12-power
	M_HP13      = 232, // harm-13-power
	M_HP14      = 233, // harm-14-power
	M_HP15      = 234, // harm-15-power
	M_HP16      = 235, // harm-16-power
	M_HPA0      = 236, // harm-010-power
	M_HPA1      = 237, // harm-011-power
	M_HPA2      = 238, // harm-012-power
	M_HPA3      = 239, // harm-013-power
	M_HPA4      = 240, // harm-014-power
	M_HPA5      = 241, // harm-015-power
	M_HPA6      = 242, // harm-016-power
	M_HPX1      = 243, // harm-001-power
	M_HPX2      = 244, // harm-002-power
	M_HPX3      = 245, // harm-003-power
	M_HPX4      = 246, // harm-004-power
	M_HPX5      = 247, // harm-005-power
	M_HPX6      = 248, // harm-006-power
	M_HPX7      = 249, // harm-007-power
	M_HPX8      = 250, // harm-008-power
	M_HPX9      = 251, // harm-009-power
	M_HPZ1      = 252, // harm-01-power
	M_HPZ2      = 253, // harm-02-power
	M_HPZ3      = 254, // harm-03-power
	M_HPZ4      = 255, // harm-04-power
	M_HPZ5      = 256, // harm-05-power
	M_HPZ6      = 257, // harm-06-power
	M_HPZ7      = 258, // harm-07-power
	M_HPZ8      = 259, // harm-08-power
	M_HPZ9      = 260, // harm-09-power
	M_HRAG      = 261, // h-reference-angle
	M_HSRM      = 262, // h-sensor-resolution-min
	M_HTAG      = 263, // h-target-angle
	M_HTOF      = 264, // h-target-offset
	M_HUMY      = 265, // humidity
	M_HV01      = 266, // harm-1-voltage
	M_HV02      = 267, // harm-2-voltage
	M_HV03      = 268, // harm-3-voltage
	M_HV04      = 269, // harm-4-voltage
	M_HV05      = 270, // harm-5-voltage
	M_HV06      = 271, // harm-6-voltage
	M_HV07      = 272, // harm-7-voltage
	M_HV08      = 273, // harm-8-voltage
	M_HV09      = 274, // harm-9-voltage
	M_HV10      = 275, // harm-10-voltage
	M_HV11      = 276, // harm-11-voltage
	M_HV12      = 277, // harm-12-voltage
	M_HV13      = 278, // harm-13-voltage
	M_HV14      = 279, // harm-14-voltage
	M_HV15      = 280, // harm-15-voltage
	M_HV16      = 281, // harm-16-voltage
	M_HVA0      = 282, // harm-010-voltage
	M_HVA1      = 283, // harm-011-voltage
	M_HVA2      = 284, // harm-012-voltage
	M_HVA3      = 285, // harm-013-voltage
	M_HVA4      = 286, // harm-014-voltage
	M_HVA5      = 287, // harm-015-voltage
	M_HVA6      = 288, // harm-016-voltage
	M_HVX1      = 289, // harm-001-voltage
	M_HVX2      = 290, // harm-002-voltage
	M_HVX3      = 291, // harm-003-voltage
	M_HVX4      = 292, // harm-004-voltage
	M_HVX5      = 293, // harm-005-voltage
	M_HVX6      = 294, // harm-006-voltage
	M_HVX7      = 295, // harm-007-voltage
	M_HVX8      = 296, // harm-008-voltage
	M_HVX9      = 297, // harm-009-voltage
	M_HVZ1      = 298, // harm-01-voltage
	M_HVZ2      = 299, // harm-02-voltage
	M_HVZ3      = 300, // harm-03-voltage
	M_HVZ4      = 301, // harm-04-voltage
	M_HVZ5      = 302, // harm-05-voltage
	M_HVZ6      = 303, // harm-06-voltage
	M_HVZ7      = 304, // harm-07-voltage
	M_HVZ8      = 305, // harm-08-voltage
	M_HVZ9      = 306, // harm-09-voltage
	M_IASP      = 307, // ias
	M_IATO      = 308, // interrupt-ack-timeout
	M_ICWB      = 309, // invalid-command-word-bit
	M_IDSE      = 310, // ident-sig-ep
	M_IDSF      = 311, // ident-sig-freq
	M_IDSG      = 312, // ident-sig
	M_IDSM      = 313, // ident-sig-mod
	M_IDWB      = 314, // invalid-data-word-bit
	M_IJIT      = 315, // int-jitter
	M_ILLU      = 316, // illum
	M_INDU      = 317, // ind
	M_INTG      = 318, // integrate
	M_INTL      = 319, // interval
	M_IRAT      = 320, // int-rate
	M_ISTI      = 321, // illegal-state-indicator
	M_ISWB      = 322, // invalid-status-word-bit
	M_ITER      = 323, // iterate
	M_ITRO      = 324, // intensity-ratio
	M_IVCW      = 325, // invalid-command-word
	M_IVDL      = 326, // invalid-data-word-length
	M_IVDP      = 327, // invalid-data-word-parity
	M_IVDS      = 328, // invalid-data-word-sync
	M_IVDT      = 329, // invalid-data-word-tr
	M_IVDW      = 330, // invalid-data-word
	M_IVMG      = 331, // invalid-message-gap
	M_IVOA      = 332, // invalid-one-amplitude
	M_IVRT      = 333, // invalid-response-time
	M_IVSW      = 334, // invalid-status-word
	M_IVWC      = 335, // invalid-word-count
	M_IVWG      = 336, // invalid-word-gap
	M_IVWL      = 337, // invalid-word-length
	M_IVZA      = 338, // invalid-zero-amplitude
	M_IVZC      = 339, // invalid-zero-crossing
	M_LDFM      = 340, // load-from
	M_LDTO      = 341, // load-to
	M_LDVW      = 342, // load-wave
	M_LINE      = 343, // line
	M_LIPF      = 344, // lines-per-channel
	M_LMDF      = 345, // lo-mod-freq
	M_LMIN      = 346, // lum-int
	M_LOCL      = 347, // localizer
	M_LRAN      = 348, // lst-reference-angle
	M_LSAE      = 349, // los-align-error
	M_LSTG      = 350, // laser-stage
	M_LUMF      = 351, // lum-flux
	M_LUMI      = 352, // luminance
	M_LUMT      = 353, // lum-temp
	M_MAGB      = 354, // mag-bearing
	M_MAGR      = 355, // mag-bearing-rate
	M_MAMP      = 356, // mod-ampl
	M_MANI      = 357, // manual-intervention
	M_MASF      = 358, // mass-flow
	M_MASK      = 359, // mask-one
	M_MATH      = 360, // math
	M_MAXT      = 361, // max-time
	M_MBAT      = 362, // main-beam-atten
	M_MDPN      = 363, // mod-pneg
	M_MDPP      = 364, // mod-ppos
	M_MDSC      = 365, // mod-source
	M_MGAP      = 366, // message-gap
	M_MMOD      = 367, // mean-mod
	M_MODD      = 368, // mod-dist
	M_MODE      = 369, // mode
	M_MODF      = 370, // mod-freq
	M_MODO      = 371, // mod-offset
	M_MODP      = 372, // mod-phase
	M_MPFM      = 373, // multp-from
	M_MPTO      = 374, // multp-to
	M_MRCO      = 375, // min-resolv-contrast
	M_MRKB      = 376, // marker-beacon
	M_MRTD      = 377, // min-resolv-temp-diff
	M_MSKZ      = 378, // mask-zero
	M_MSNR      = 379, // minimum-sense-rate
	M_MTFD      = 380, // mtf-direction
	M_MTFP      = 381, // mtf-freq-points
	M_MTFU      = 382, // modulation-transfer-function
	M_NCTO      = 383, // no-command-timeout
	M_NEDT      = 384, // noise-eq-diff-temp
	M_NEGS      = 385, // neg-slope
	M_NHAR      = 386, // non-harmonics
	M_NLIN      = 387, // non-lin
	M_NOAD      = 388, // noise-ampl-dens
	M_NOAV      = 389, // noise-av
	M_NOIS      = 390, // noise
	M_NOPD      = 391, // noise-pwr-dens
	M_NOPK      = 392, // noise-p
	M_NOPP      = 393, // noise-pp
	M_NOTR      = 394, // noise-trms
	M_NPWT      = 395, // neg-pulse-width
	M_NRTO      = 396, // no-response-timeout
	M_OAMP      = 397, // one-amplitude
	M_OTMP      = 398, // oper-temp
	M_OVER      = 399, // overshoot
	M_P3DV      = 400, // p3-dev
	M_P3LV      = 401, // p3-level
	M_PAMP      = 402, // p-ampl
	M_PANG      = 403, // phase-angle
	M_PARE      = 404, // parity-even
	M_PARO      = 405, // parity-odd
	M_PAST      = 406, // pulse-ampl-stab
	M_PATH      = 407, // path
	M_PATN      = 408, // pulse-atten
	M_PATT      = 409, // pattern
	M_PCCU      = 410, // pac-coupl
	M_PCLS      = 411, // pulse-class
	M_PCSR      = 412, // pac-source
	M_PDEV      = 413, // phase-dev
	M_PDGN      = 414, // peak-degen
	M_PDRP      = 415, // pair-droop
	M_PDVN      = 416, // phase-dev-pn
	M_PDVP      = 417, // phase-dev-pp
	M_PERI      = 418, // period
	M_PEST      = 419, // pulse-energy-stab
	M_PHPN      = 420, // phase-pneg
	M_PHPP      = 421, // phase-ppos
	M_PJIT      = 422, // phase-jit
	M_PKDV      = 423, // peak-dev
	M_PLAN      = 424, // pla
	M_PLAR      = 425, // pla-rate
	M_PLEG      = 426, // pulse-energy
	M_PLID      = 427, // pulse-ident
	M_PLSE      = 428, // pulses-excl
	M_PLSI      = 429, // pulses-incl
	M_PLWD      = 430, // pulse-width
	M_PMCU      = 431, // pm-coupl
	M_PMFQ      = 432, // pm-freq
	M_PMSR      = 433, // pm-source
	M_PODN      = 434, // power-dens
	M_POSI      = 435, // position
	M_POSS      = 436, // pos-slope
	M_POWA      = 437, // power-av
	M_POWP      = 438, // power-p
	M_POWR      = 439, // power
	M_PPOS      = 440, // pulse-posn
	M_PPST      = 441, // pulse-period-stab
	M_PPWT      = 442, // pos-pulse-width
	M_PRCD      = 443, // proceed
	M_PRDF      = 444, // power-diff
	M_PRFR      = 445, // prf
	M_PRIO      = 446, // priority
	M_PROA      = 447, // press-osc-ampl
	M_PROF      = 448, // press-osc-freq
	M_PRSA      = 449, // press-a
	M_PRSG      = 450, // press-g
	M_PRSR      = 451, // press-rate
	M_PRTY      = 452, // parity
	M_PSHI      = 453, // phase-shift
	M_PSHT      = 454, // preshoot
	M_PSPC      = 455, // pair-spacing
	M_PSPE      = 456, // pulse-spect
	M_PSPT      = 457, // pulse-spect-threshold
	M_PSRC      = 458, // peak-search
	M_PTCP      = 459, // tcp
	M_PUDP      = 460, // udp
	M_PWRL      = 461, // pwr-lmt
	M_QFAC      = 462, // q
	M_QUAD      = 463, // quad
	M_RADL      = 464, // radial
	M_RADR      = 465, // radial-rate
	M_RAIL      = 466, // radiance-interval
	M_RASP      = 467, // radiance-stop
	M_RAST      = 468, // radiance-start
	M_RCVS      = 469, // receiver-sensitivity
	M_RDNC      = 470, // radiance
	M_REAC      = 471, // reactance
	M_REFF      = 472, // ref-freq
	M_REFI      = 473, // ref-inertial
	M_REFM      = 474, // reference-mirror-size
	M_REFP      = 475, // ref-power
	M_REFR      = 476, // ref-res
	M_REFS      = 477, // ref-source
	M_REFU      = 478, // ref-uut
	M_REFV      = 479, // ref-volt
	M_REFX      = 480, // ref
	M_RELB      = 481, // rel-bearing
	M_RELH      = 482, // relative-humidity
	M_RELW      = 483, // relative-wind
	M_REPT      = 484, // repeat
	M_RERR      = 485, // range-error
	M_RESB      = 486, // resolution-bandwidth
	M_RESI      = 487, // res
	M_RESP      = 488, // resp
	M_RESR      = 489, // res-ratio
	M_RING      = 490, // ringing
	M_RISE      = 491, // rise-time
	M_RLBR      = 492, // rel-bearing-rate
	M_RLVL      = 493, // radiance-level-count
	M_RMNS      = 494, // ramp-neg-slope
	M_RMOD      = 495, // ranging-mode
	M_RMPS      = 496, // ramp-pos-slope
	M_ROUN      = 497, // rounding
	M_RPDV      = 498, // range-pulse-dev
	M_RPEC      = 499, // range-pulse-echo
	M_RPHF      = 500, // ref-phase-freq
	M_RPLD      = 501, // ref-pulses-dev
	M_RPLE      = 502, // reply-eff
	M_RPLI      = 503, // ref-pulses-incl
	M_RPLX      = 504, // ref-pulses-excl
	M_RSPH      = 505, // resp-hiz
	M_RSPO      = 506, // resp-one
	M_RSPT      = 507, // response-time
	M_RSPZ      = 508, // resp-zero
	M_RTRS      = 509, // rotor-speed
	M_SASP      = 510, // sample-spacing
	M_SATM      = 511, // sample-time
	M_SBCF      = 512, // sub-car-freq
	M_SBCM      = 513, // sub-car-mod
	M_SBEV      = 514, // strobe-to-event
	M_SBFM      = 515, // subtract-from
	M_SBTO      = 516, // subtract-to
	M_SCNT      = 517, // sample-count
	M_SDEL      = 518, // sense-delay
	M_SERL      = 519, // serial-lsb-first
	M_SERM      = 520, // serial-msb-first
	M_SESA      = 521, // sensor-aperture
	M_SETT      = 522, // settle-time
	M_SGNO      = 523, // sig-noise
	M_SGTF      = 524, // sig-transfer-function
	M_SHFS      = 525, // shaft-speed
	M_SIMU      = 526, // do-simultaneous
	M_SITF      = 527, // sys-intens-transfer-function
	M_SKEW      = 528, // skew-time
	M_SLEW      = 529, // slew-rate
	M_SLRA      = 530, // slant-range-accel
	M_SLRG      = 531, // slant-range
	M_SLRR      = 532, // slant-range-rate
	M_SLSD      = 533, // sls-dev
	M_SLSL      = 534, // sls-level
	M_SMAV      = 535, // sample-av
	M_SMPL      = 536, // sample
	M_SMPW      = 537, // sample-width
	M_SMTH      = 538, // smooth
	M_SNAD      = 539, // sinad
	M_SNFL      = 540, // single-filter
	M_SNSR      = 541, // sense-rate
	M_SPCG      = 542, // spacing
	M_SPED      = 543, // speed
	M_SPGR      = 544, // spec-grav
	M_SPRT      = 545, // speed-ratio
	M_SPTM      = 546, // spec-temp
	M_SQD1      = 547, // sqtr-dist-1
	M_SQD2      = 548, // sqtr-dist-2
	M_SQD3      = 549, // sqtr-dist-3
	M_SQTD      = 550, // sqtr-dist
	M_SQTR      = 551, // sqtr-rate
	M_SRFR      = 552, // sensor-freq
	M_SSMD      = 553, // sensitivity-mode
	M_STAT      = 554, // status
	M_STIM      = 555, // stim
	M_STLN      = 556, // start-line
	M_STMH      = 557, // stim-hiz
	M_STMO      = 558, // stim-one
	M_STMP      = 559, // static-temp
	M_STMR      = 560, // stim-rate
	M_STMZ      = 561, // stim-zero
	M_STOP      = 562, // stop
	M_STPA      = 563, // static-press-a
	M_STPB      = 564, // stop-bits
	M_STPG      = 565, // static-press-g
	M_STPR      = 566, // static-press-rate
	M_STPT      = 567, // set-of-points
	M_STRD      = 568, // standard
	M_STRT      = 569, // start
	M_STUT      = 570, // start-unit
	M_STWD      = 571, // status-word
	M_SUSP      = 572, // susceptance
	M_SVCP      = 573, // save-comp
	M_SVFM      = 574, // save-from
	M_SVTO      = 575, // save-to
	M_SVWV      = 576, // save-wave
	M_SWBT      = 577, // status-word-bit
	M_SWPT      = 578, // sweep-time
	M_SWRA      = 579, // swr
	M_SYDL      = 580, // sync-delay
	M_SYEV      = 581, // sync-to-event
	M_SYNC      = 582, // sync
	M_TASP      = 583, // tas
	M_TASY      = 584, // time-asym
	M_TCAP      = 585, // temp-coeff-cap
	M_TCBT      = 586, // tgt-coordinate-bottom
	M_TCLT      = 587, // tgt-coordinate-left
	M_TCRT      = 588, // tgt-coordinate-right
	M_TCTP      = 589, // tgt-coordinate-top
	M_TCUR      = 590, // temp-coeff-current
	M_TDAT      = 591, // target-data
	M_TEFC      = 592, // test-freq-count
	M_TEMP      = 593, // temp
	M_TEQL      = 594, // test-equip-listener
	M_TEQT      = 595, // test-equip-talker
	M_TERM      = 596, // terminated
	M_TGMD      = 597, // trigger-mode
	M_TGPL      = 598, // target-polarity
	M_TGTA      = 599, // target-range-accel
	M_TGTD      = 600, // target-range
	M_TGTH      = 601, // target-threshold
	M_TGTP      = 602, // target-type
	M_TGTR      = 603, // target-range-rate
	M_TGTS      = 604, // last-pulse-range
	M_THRT      = 605, // thrust
	M_THSM      = 606, // three-samples
	M_TIEV      = 607, // time-every
	M_TILT      = 608, // tilt
	M_TIME      = 609, // time
	M_TIMP      = 610, // test-equip-imp
	M_TIND      = 611, // temp-coeff-ind
	M_TIUN      = 612, // time-until
	M_TIWH      = 613, // time-when
	M_TJIT      = 614, // time-jit
	M_TLAX      = 615, // tilt-axis
	M_TMON      = 616, // test-equip-monitor
	M_TMVL      = 617, // timing-value
	M_TOPA      = 618, // total-press-a
	M_TOPG      = 619, // total-press-g
	M_TOPR      = 620, // total-press-rate
	M_TORQ      = 621, // torque
	M_TPHD      = 622, // three-phase-delta
	M_TPHY      = 623, // three-phase-wye
	M_TREA      = 624, // temp-coeff-react
	M_TRES      = 625, // temp-coeff-res
	M_TRGS      = 626, // trig-source
	M_TRIG      = 627, // trig
	M_TRLV      = 628, // trig-level
	M_TRN0      = 629, // trans-zero
	M_TRN1      = 630, // trans-one
	M_TRNP      = 631, // trans-period
	M_TRNS      = 632, // trans-sync
	M_TROL      = 633, // test-equip-role
	M_TRSL      = 634, // trig-slope
	M_TRUE      = 635, // true
	M_TRUN      = 636, // timer-until
	M_TRWH      = 637, // timer-when
	M_TSAC      = 638, // test-area-count
	M_TSCC      = 639, // test-chan-count
	M_TSIM      = 640, // test-equip-simulate
	M_TSPC      = 641, // test-point-count
	M_TSTF      = 642, // test-field
	M_TTMP      = 643, // total-temp
	M_TVOL      = 644, // temp-coeff-volt
	M_TYPE      = 645, // type
	M_UNDR      = 646, // undershoot
	M_UNFY      = 647, // uniformity
	M_UNIT      = 648, // unit
	M_UUPL      = 649, // units-per-line
	M_UUTL      = 650, // uut-listener
	M_UUTT      = 651, // uut-talker
	M_VALU      = 652, // value
	M_VBAC      = 653, // vibration-accel
	M_VBAN      = 654, // video-bandwidth
	M_VBAP      = 655, // vibration-ampl-p
	M_VBPP      = 656, // vibration-ampl-pp
	M_VBRT      = 657, // vibration-rate
	M_VBTR      = 658, // vibration-ampl-trms
	M_VDIV      = 659, // volt-per-div
	M_VEAO      = 660, // event-after-occurrences-value
	M_VEDL      = 661, // event-delay-value
	M_VEEO      = 662, // event-each-occurrence-value
	M_VEFO      = 663, // event-first-occurrence-value
	M_VEGF      = 664, // event-gate-for
	M_VETF      = 665, // event-time-for
	M_VFOV      = 666, // v-field-of-view
	M_VINS      = 667, // voltage-inst
	M_VIST      = 668, // video-sync-type
	M_VLAE      = 669, // v-los-align-error
	M_VLAV      = 670, // av-voltage
	M_VLPK      = 671, // voltage-p
	M_VLPP      = 672, // voltage-pp
	M_VLT0      = 673, // voltage-zero
	M_VLT1      = 674, // voltage-one
	M_VLTL      = 675, // volt-lmt
	M_VLTQ      = 676, // voltage-quies
	M_VLTR      = 677, // voltage-ramped
	M_VLTS      = 678, // voltage-stepped
	M_VOLF      = 679, // volume-flow
	M_VOLR      = 680, // voltage-ratio
	M_VOLT      = 681, // voltage
	M_VPHF      = 682, // var-phase-freq
	M_VPHM      = 683, // var-phase-mod
	M_VPKN      = 684, // voltage-p-neg
	M_VPKP      = 685, // voltage-p-pos
	M_VRAG      = 686, // v-reference-angle
	M_VRMS      = 687, // voltage-trms
	M_VSRM      = 688, // v-sensor-resolution-min
	M_VTAG      = 689, // v-target-angle
	M_VTOF      = 690, // v-target-offset
	M_WAIT      = 691, // wait
	M_WAVE      = 692, // wave-length
	M_WDLN      = 693, // word-length
	M_WDRT      = 694, // word-rate
	M_WGAP      = 695, // word-gap
	M_WILD      = 696, // wild
	M_WIND      = 697, // wind-speed
	M_WRDC      = 698, // word-count
	M_WTRN      = 699, // word-transition
	M_XACE      = 700, // x-autocollimation-error
	M_XAGR      = 701, // x-angle-of-regard
	M_XBAG      = 702, // x-boresight-angle
	M_XTAR      = 703, // x-target-angle
	M_YACE      = 704, // y-autocollimation-error
	M_YAGR      = 705, // y-angle-of-regard
	M_YBAG      = 706, // y-boresight-angle
	M_YTAR      = 707, // y-target-angle
	M_ZAMP      = 708, // zero-amplitude
	M_ZCRS      = 709, // zero-crossing
	M_ZERO      = 710, // zero-index
	M__CNT      = 711, // symbol count
};
//
//	MODULETYPES
//
enum enumTyxModuletypes {
	T_ACS       =   1, // name not available
	T_API       =   2, // name not available
	T_ARB       =   3, // name not available
	T_ASA       =   4, // name not available
	T_DCS       =   5, // name not available
	T_DIG       =   6, // name not available
	T_DMM       =   7, // name not available
	T_DWG       =   8, // name not available
	T_FNG       =   9, // name not available
	T_FTM       =  10, // name not available
	T_MBT       =  11, // name not available
	T_MFU       =  12, // name not available
	T_MTR       =  13, // name not available
	T_PAT       =  14, // name not available
	T_PCM       =  15, // name not available
	T_PLG       =  16, // name not available
	T_PSS       =  17, // name not available
	T_PWM       =  18, // name not available
	T_QAL       =  19, // name not available
	T_RSV       =  20, // name not available
	T_RSY       =  21, // name not available
	T_SNG       =  22, // name not available
	T_SRS       =  23, // name not available
	T_VDG       =  24, // name not available
	T__CNT      =  25, // symbol count
};
//
//	DIMS-A
//
enum enumTyxDimsA {
	D_1553A     =   1, // mil-1553a
	D_1553B     =   2, // mil-1553b
	D_AFAPD     =   3, // afapd
	D_ALLLS     =   4, // all-listener
	D_AMI       =   5, // ami
	D_AR429     =   6, // arinc-429
	D_ARDC      =   7, // ardc
	D_BIP       =   8, // bip
	D_CAN       =   9, // can
	D_CDDI      =  10, // cddi
	D_CONMD     =  11, // con-mode
	D_CONRT     =  12, // con-rt
	D_CSM       =  13, // csm
	D_CSN       =  14, // csn
	D_CSOC      =  15, // consecutive-occurrences
	D_ETHERNET  =  16, // ethernet
	D_EVEN      =  17, // even
	D_HDB       =  18, // hdb
	D_ICAN      =  19, // ican
	D_ICAO      =  20, // icao
	D_IDL       =  21, // idl
	D_IEEE488   =  22, // ieee-488
	D_LNGTH     =  23, // length
	D_MARK      =  24, // mark
	D_MASTR     =  25, // master
	D_MIC       =  26, // mic
	D_MIP       =  27, // mip
	D_MONTR     =  28, // monitor
	D_MTS       =  29, // mts
	D_NONE      =  30, // none
	D_NRZ       =  31, // nrz
	D_ODD       =  32, // odd
	D_OFF       =  33, // off
	D_ON        =  34, // on
	D_PARA      =  35, // parallel
	D_PRIM      =  36, // primary
	D_PRTY      =  37, // parity
	D_REDT      =  38, // redundant
	D_RS232     =  39, // rs-232
	D_RS422     =  40, // rs-422
	D_RS485     =  41, // rs-485
	D_RTCON     =  42, // rt-con
	D_RTRT      =  43, // rt-rt
	D_RZ        =  44, // rz
	D_SERL      =  45, // serial-lsb-first
	D_SERM      =  46, // serial-msb-first
	D_SLAVE     =  47, // slave
	D_SYNC      =  48, // sync
	D_TACFIRE   =  49, // tacfire
	D_TLKLS     =  50, // talker-listener
	D_TR        =  51, // t-r
	D_WADC      =  52, // wadc
	D__CNT      =  53, // symbol count
};
//
//	DIMS-B
//
enum enumTyxDimsB {
	R__CNT      =   1, // symbol count
};
#endif // _LEXKEY_H_
