/* soapH.h
   Generated by gSOAP 2.7.6c from atxml.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
#endif

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (86)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (85)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_atxml__IssueDriverFunctionCall
#define SOAP_TYPE_atxml__IssueDriverFunctionCall (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueDriverFunctionCall(struct soap*, const struct atxml__IssueDriverFunctionCall *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueDriverFunctionCall(struct soap*, struct atxml__IssueDriverFunctionCall *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueDriverFunctionCall(struct soap*, const struct atxml__IssueDriverFunctionCall *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueDriverFunctionCall(struct soap*, const char*, int, const struct atxml__IssueDriverFunctionCall *, const char*);
SOAP_FMAC3 struct atxml__IssueDriverFunctionCall * SOAP_FMAC4 soap_get_atxml__IssueDriverFunctionCall(struct soap*, struct atxml__IssueDriverFunctionCall *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueDriverFunctionCall * SOAP_FMAC4 soap_in_atxml__IssueDriverFunctionCall(struct soap*, const char*, struct atxml__IssueDriverFunctionCall *, const char*);

#ifndef SOAP_TYPE_atxml__IssueDriverFunctionCallResponse
#define SOAP_TYPE_atxml__IssueDriverFunctionCallResponse (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueDriverFunctionCallResponse(struct soap*, const struct atxml__IssueDriverFunctionCallResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueDriverFunctionCallResponse(struct soap*, struct atxml__IssueDriverFunctionCallResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueDriverFunctionCallResponse(struct soap*, const struct atxml__IssueDriverFunctionCallResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueDriverFunctionCallResponse(struct soap*, const char*, int, const struct atxml__IssueDriverFunctionCallResponse *, const char*);
SOAP_FMAC3 struct atxml__IssueDriverFunctionCallResponse * SOAP_FMAC4 soap_get_atxml__IssueDriverFunctionCallResponse(struct soap*, struct atxml__IssueDriverFunctionCallResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueDriverFunctionCallResponse * SOAP_FMAC4 soap_in_atxml__IssueDriverFunctionCallResponse(struct soap*, const char*, struct atxml__IssueDriverFunctionCallResponse *, const char*);

#ifndef SOAP_TYPE_atxml__IssueNativeCmds
#define SOAP_TYPE_atxml__IssueNativeCmds (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueNativeCmds(struct soap*, const struct atxml__IssueNativeCmds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueNativeCmds(struct soap*, struct atxml__IssueNativeCmds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueNativeCmds(struct soap*, const struct atxml__IssueNativeCmds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueNativeCmds(struct soap*, const char*, int, const struct atxml__IssueNativeCmds *, const char*);
SOAP_FMAC3 struct atxml__IssueNativeCmds * SOAP_FMAC4 soap_get_atxml__IssueNativeCmds(struct soap*, struct atxml__IssueNativeCmds *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueNativeCmds * SOAP_FMAC4 soap_in_atxml__IssueNativeCmds(struct soap*, const char*, struct atxml__IssueNativeCmds *, const char*);

#ifndef SOAP_TYPE_atxml__IssueNativeCmdsResponse
#define SOAP_TYPE_atxml__IssueNativeCmdsResponse (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueNativeCmdsResponse(struct soap*, const struct atxml__IssueNativeCmdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueNativeCmdsResponse(struct soap*, struct atxml__IssueNativeCmdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueNativeCmdsResponse(struct soap*, const struct atxml__IssueNativeCmdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueNativeCmdsResponse(struct soap*, const char*, int, const struct atxml__IssueNativeCmdsResponse *, const char*);
SOAP_FMAC3 struct atxml__IssueNativeCmdsResponse * SOAP_FMAC4 soap_get_atxml__IssueNativeCmdsResponse(struct soap*, struct atxml__IssueNativeCmdsResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueNativeCmdsResponse * SOAP_FMAC4 soap_in_atxml__IssueNativeCmdsResponse(struct soap*, const char*, struct atxml__IssueNativeCmdsResponse *, const char*);

#ifndef SOAP_TYPE_atxml__IssueIst
#define SOAP_TYPE_atxml__IssueIst (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueIst(struct soap*, const struct atxml__IssueIst *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueIst(struct soap*, struct atxml__IssueIst *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueIst(struct soap*, const struct atxml__IssueIst *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueIst(struct soap*, const char*, int, const struct atxml__IssueIst *, const char*);
SOAP_FMAC3 struct atxml__IssueIst * SOAP_FMAC4 soap_get_atxml__IssueIst(struct soap*, struct atxml__IssueIst *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueIst * SOAP_FMAC4 soap_in_atxml__IssueIst(struct soap*, const char*, struct atxml__IssueIst *, const char*);

#ifndef SOAP_TYPE_atxml__IssueIstResponse
#define SOAP_TYPE_atxml__IssueIstResponse (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueIstResponse(struct soap*, const struct atxml__IssueIstResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueIstResponse(struct soap*, struct atxml__IssueIstResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueIstResponse(struct soap*, const struct atxml__IssueIstResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueIstResponse(struct soap*, const char*, int, const struct atxml__IssueIstResponse *, const char*);
SOAP_FMAC3 struct atxml__IssueIstResponse * SOAP_FMAC4 soap_get_atxml__IssueIstResponse(struct soap*, struct atxml__IssueIstResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueIstResponse * SOAP_FMAC4 soap_in_atxml__IssueIstResponse(struct soap*, const char*, struct atxml__IssueIstResponse *, const char*);

#ifndef SOAP_TYPE_atxml__IssueTestResultsFile
#define SOAP_TYPE_atxml__IssueTestResultsFile (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueTestResultsFile(struct soap*, const struct atxml__IssueTestResultsFile *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueTestResultsFile(struct soap*, struct atxml__IssueTestResultsFile *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueTestResultsFile(struct soap*, const struct atxml__IssueTestResultsFile *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueTestResultsFile(struct soap*, const char*, int, const struct atxml__IssueTestResultsFile *, const char*);
SOAP_FMAC3 struct atxml__IssueTestResultsFile * SOAP_FMAC4 soap_get_atxml__IssueTestResultsFile(struct soap*, struct atxml__IssueTestResultsFile *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueTestResultsFile * SOAP_FMAC4 soap_in_atxml__IssueTestResultsFile(struct soap*, const char*, struct atxml__IssueTestResultsFile *, const char*);

#ifndef SOAP_TYPE_atxml__IssueTestResultsFileResponse
#define SOAP_TYPE_atxml__IssueTestResultsFileResponse (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueTestResultsFileResponse(struct soap*, const struct atxml__IssueTestResultsFileResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueTestResultsFileResponse(struct soap*, struct atxml__IssueTestResultsFileResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueTestResultsFileResponse(struct soap*, const struct atxml__IssueTestResultsFileResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueTestResultsFileResponse(struct soap*, const char*, int, const struct atxml__IssueTestResultsFileResponse *, const char*);
SOAP_FMAC3 struct atxml__IssueTestResultsFileResponse * SOAP_FMAC4 soap_get_atxml__IssueTestResultsFileResponse(struct soap*, struct atxml__IssueTestResultsFileResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueTestResultsFileResponse * SOAP_FMAC4 soap_in_atxml__IssueTestResultsFileResponse(struct soap*, const char*, struct atxml__IssueTestResultsFileResponse *, const char*);

#ifndef SOAP_TYPE_atxml__IssueTestResults
#define SOAP_TYPE_atxml__IssueTestResults (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueTestResults(struct soap*, const struct atxml__IssueTestResults *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueTestResults(struct soap*, struct atxml__IssueTestResults *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueTestResults(struct soap*, const struct atxml__IssueTestResults *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueTestResults(struct soap*, const char*, int, const struct atxml__IssueTestResults *, const char*);
SOAP_FMAC3 struct atxml__IssueTestResults * SOAP_FMAC4 soap_get_atxml__IssueTestResults(struct soap*, struct atxml__IssueTestResults *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueTestResults * SOAP_FMAC4 soap_in_atxml__IssueTestResults(struct soap*, const char*, struct atxml__IssueTestResults *, const char*);

#ifndef SOAP_TYPE_atxml__IssueTestResultsResponse
#define SOAP_TYPE_atxml__IssueTestResultsResponse (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueTestResultsResponse(struct soap*, const struct atxml__IssueTestResultsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueTestResultsResponse(struct soap*, struct atxml__IssueTestResultsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueTestResultsResponse(struct soap*, const struct atxml__IssueTestResultsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueTestResultsResponse(struct soap*, const char*, int, const struct atxml__IssueTestResultsResponse *, const char*);
SOAP_FMAC3 struct atxml__IssueTestResultsResponse * SOAP_FMAC4 soap_get_atxml__IssueTestResultsResponse(struct soap*, struct atxml__IssueTestResultsResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueTestResultsResponse * SOAP_FMAC4 soap_in_atxml__IssueTestResultsResponse(struct soap*, const char*, struct atxml__IssueTestResultsResponse *, const char*);

#ifndef SOAP_TYPE_atxml__InvokeRemoveAllSequence
#define SOAP_TYPE_atxml__InvokeRemoveAllSequence (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__InvokeRemoveAllSequence(struct soap*, const struct atxml__InvokeRemoveAllSequence *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__InvokeRemoveAllSequence(struct soap*, struct atxml__InvokeRemoveAllSequence *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__InvokeRemoveAllSequence(struct soap*, const struct atxml__InvokeRemoveAllSequence *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__InvokeRemoveAllSequence(struct soap*, const char*, int, const struct atxml__InvokeRemoveAllSequence *, const char*);
SOAP_FMAC3 struct atxml__InvokeRemoveAllSequence * SOAP_FMAC4 soap_get_atxml__InvokeRemoveAllSequence(struct soap*, struct atxml__InvokeRemoveAllSequence *, const char*, const char*);
SOAP_FMAC3 struct atxml__InvokeRemoveAllSequence * SOAP_FMAC4 soap_in_atxml__InvokeRemoveAllSequence(struct soap*, const char*, struct atxml__InvokeRemoveAllSequence *, const char*);

#ifndef SOAP_TYPE_atxml__InvokeRemoveAllSequenceResponse
#define SOAP_TYPE_atxml__InvokeRemoveAllSequenceResponse (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__InvokeRemoveAllSequenceResponse(struct soap*, const struct atxml__InvokeRemoveAllSequenceResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__InvokeRemoveAllSequenceResponse(struct soap*, struct atxml__InvokeRemoveAllSequenceResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__InvokeRemoveAllSequenceResponse(struct soap*, const struct atxml__InvokeRemoveAllSequenceResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__InvokeRemoveAllSequenceResponse(struct soap*, const char*, int, const struct atxml__InvokeRemoveAllSequenceResponse *, const char*);
SOAP_FMAC3 struct atxml__InvokeRemoveAllSequenceResponse * SOAP_FMAC4 soap_get_atxml__InvokeRemoveAllSequenceResponse(struct soap*, struct atxml__InvokeRemoveAllSequenceResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__InvokeRemoveAllSequenceResponse * SOAP_FMAC4 soap_in_atxml__InvokeRemoveAllSequenceResponse(struct soap*, const char*, struct atxml__InvokeRemoveAllSequenceResponse *, const char*);

#ifndef SOAP_TYPE_atxml__InvokeApplyAllSequence
#define SOAP_TYPE_atxml__InvokeApplyAllSequence (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__InvokeApplyAllSequence(struct soap*, const struct atxml__InvokeApplyAllSequence *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__InvokeApplyAllSequence(struct soap*, struct atxml__InvokeApplyAllSequence *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__InvokeApplyAllSequence(struct soap*, const struct atxml__InvokeApplyAllSequence *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__InvokeApplyAllSequence(struct soap*, const char*, int, const struct atxml__InvokeApplyAllSequence *, const char*);
SOAP_FMAC3 struct atxml__InvokeApplyAllSequence * SOAP_FMAC4 soap_get_atxml__InvokeApplyAllSequence(struct soap*, struct atxml__InvokeApplyAllSequence *, const char*, const char*);
SOAP_FMAC3 struct atxml__InvokeApplyAllSequence * SOAP_FMAC4 soap_in_atxml__InvokeApplyAllSequence(struct soap*, const char*, struct atxml__InvokeApplyAllSequence *, const char*);

#ifndef SOAP_TYPE_atxml__InvokeApplyAllSequenceResponse
#define SOAP_TYPE_atxml__InvokeApplyAllSequenceResponse (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__InvokeApplyAllSequenceResponse(struct soap*, const struct atxml__InvokeApplyAllSequenceResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__InvokeApplyAllSequenceResponse(struct soap*, struct atxml__InvokeApplyAllSequenceResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__InvokeApplyAllSequenceResponse(struct soap*, const struct atxml__InvokeApplyAllSequenceResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__InvokeApplyAllSequenceResponse(struct soap*, const char*, int, const struct atxml__InvokeApplyAllSequenceResponse *, const char*);
SOAP_FMAC3 struct atxml__InvokeApplyAllSequenceResponse * SOAP_FMAC4 soap_get_atxml__InvokeApplyAllSequenceResponse(struct soap*, struct atxml__InvokeApplyAllSequenceResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__InvokeApplyAllSequenceResponse * SOAP_FMAC4 soap_in_atxml__InvokeApplyAllSequenceResponse(struct soap*, const char*, struct atxml__InvokeApplyAllSequenceResponse *, const char*);

#ifndef SOAP_TYPE_atxml__QueryInterStatus
#define SOAP_TYPE_atxml__QueryInterStatus (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__QueryInterStatus(struct soap*, const struct atxml__QueryInterStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__QueryInterStatus(struct soap*, struct atxml__QueryInterStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__QueryInterStatus(struct soap*, const struct atxml__QueryInterStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__QueryInterStatus(struct soap*, const char*, int, const struct atxml__QueryInterStatus *, const char*);
SOAP_FMAC3 struct atxml__QueryInterStatus * SOAP_FMAC4 soap_get_atxml__QueryInterStatus(struct soap*, struct atxml__QueryInterStatus *, const char*, const char*);
SOAP_FMAC3 struct atxml__QueryInterStatus * SOAP_FMAC4 soap_in_atxml__QueryInterStatus(struct soap*, const char*, struct atxml__QueryInterStatus *, const char*);

#ifndef SOAP_TYPE_atxml__QueryInterStatusResponse
#define SOAP_TYPE_atxml__QueryInterStatusResponse (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__QueryInterStatusResponse(struct soap*, const struct atxml__QueryInterStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__QueryInterStatusResponse(struct soap*, struct atxml__QueryInterStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__QueryInterStatusResponse(struct soap*, const struct atxml__QueryInterStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__QueryInterStatusResponse(struct soap*, const char*, int, const struct atxml__QueryInterStatusResponse *, const char*);
SOAP_FMAC3 struct atxml__QueryInterStatusResponse * SOAP_FMAC4 soap_get_atxml__QueryInterStatusResponse(struct soap*, struct atxml__QueryInterStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__QueryInterStatusResponse * SOAP_FMAC4 soap_in_atxml__QueryInterStatusResponse(struct soap*, const char*, struct atxml__QueryInterStatusResponse *, const char*);

#ifndef SOAP_TYPE_atxml__IssueSignal
#define SOAP_TYPE_atxml__IssueSignal (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueSignal(struct soap*, const struct atxml__IssueSignal *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueSignal(struct soap*, struct atxml__IssueSignal *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueSignal(struct soap*, const struct atxml__IssueSignal *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueSignal(struct soap*, const char*, int, const struct atxml__IssueSignal *, const char*);
SOAP_FMAC3 struct atxml__IssueSignal * SOAP_FMAC4 soap_get_atxml__IssueSignal(struct soap*, struct atxml__IssueSignal *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueSignal * SOAP_FMAC4 soap_in_atxml__IssueSignal(struct soap*, const char*, struct atxml__IssueSignal *, const char*);

#ifndef SOAP_TYPE_atxml__IssueSignalResponse
#define SOAP_TYPE_atxml__IssueSignalResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__IssueSignalResponse(struct soap*, const struct atxml__IssueSignalResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__IssueSignalResponse(struct soap*, struct atxml__IssueSignalResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__IssueSignalResponse(struct soap*, const struct atxml__IssueSignalResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__IssueSignalResponse(struct soap*, const char*, int, const struct atxml__IssueSignalResponse *, const char*);
SOAP_FMAC3 struct atxml__IssueSignalResponse * SOAP_FMAC4 soap_get_atxml__IssueSignalResponse(struct soap*, struct atxml__IssueSignalResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__IssueSignalResponse * SOAP_FMAC4 soap_in_atxml__IssueSignalResponse(struct soap*, const char*, struct atxml__IssueSignalResponse *, const char*);

#ifndef SOAP_TYPE_atxml__SubmitUutId
#define SOAP_TYPE_atxml__SubmitUutId (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__SubmitUutId(struct soap*, const struct atxml__SubmitUutId *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__SubmitUutId(struct soap*, struct atxml__SubmitUutId *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__SubmitUutId(struct soap*, const struct atxml__SubmitUutId *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__SubmitUutId(struct soap*, const char*, int, const struct atxml__SubmitUutId *, const char*);
SOAP_FMAC3 struct atxml__SubmitUutId * SOAP_FMAC4 soap_get_atxml__SubmitUutId(struct soap*, struct atxml__SubmitUutId *, const char*, const char*);
SOAP_FMAC3 struct atxml__SubmitUutId * SOAP_FMAC4 soap_in_atxml__SubmitUutId(struct soap*, const char*, struct atxml__SubmitUutId *, const char*);

#ifndef SOAP_TYPE_atxml__SubmitUutIdResponse
#define SOAP_TYPE_atxml__SubmitUutIdResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__SubmitUutIdResponse(struct soap*, const struct atxml__SubmitUutIdResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__SubmitUutIdResponse(struct soap*, struct atxml__SubmitUutIdResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__SubmitUutIdResponse(struct soap*, const struct atxml__SubmitUutIdResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__SubmitUutIdResponse(struct soap*, const char*, int, const struct atxml__SubmitUutIdResponse *, const char*);
SOAP_FMAC3 struct atxml__SubmitUutIdResponse * SOAP_FMAC4 soap_get_atxml__SubmitUutIdResponse(struct soap*, struct atxml__SubmitUutIdResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__SubmitUutIdResponse * SOAP_FMAC4 soap_in_atxml__SubmitUutIdResponse(struct soap*, const char*, struct atxml__SubmitUutIdResponse *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterTmaSelect
#define SOAP_TYPE_atxml__RegisterTmaSelect (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterTmaSelect(struct soap*, const struct atxml__RegisterTmaSelect *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterTmaSelect(struct soap*, struct atxml__RegisterTmaSelect *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterTmaSelect(struct soap*, const struct atxml__RegisterTmaSelect *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterTmaSelect(struct soap*, const char*, int, const struct atxml__RegisterTmaSelect *, const char*);
SOAP_FMAC3 struct atxml__RegisterTmaSelect * SOAP_FMAC4 soap_get_atxml__RegisterTmaSelect(struct soap*, struct atxml__RegisterTmaSelect *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterTmaSelect * SOAP_FMAC4 soap_in_atxml__RegisterTmaSelect(struct soap*, const char*, struct atxml__RegisterTmaSelect *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterTmaSelectResponse
#define SOAP_TYPE_atxml__RegisterTmaSelectResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterTmaSelectResponse(struct soap*, const struct atxml__RegisterTmaSelectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterTmaSelectResponse(struct soap*, struct atxml__RegisterTmaSelectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterTmaSelectResponse(struct soap*, const struct atxml__RegisterTmaSelectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterTmaSelectResponse(struct soap*, const char*, int, const struct atxml__RegisterTmaSelectResponse *, const char*);
SOAP_FMAC3 struct atxml__RegisterTmaSelectResponse * SOAP_FMAC4 soap_get_atxml__RegisterTmaSelectResponse(struct soap*, struct atxml__RegisterTmaSelectResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterTmaSelectResponse * SOAP_FMAC4 soap_in_atxml__RegisterTmaSelectResponse(struct soap*, const char*, struct atxml__RegisterTmaSelectResponse *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterInstStatus
#define SOAP_TYPE_atxml__RegisterInstStatus (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterInstStatus(struct soap*, const struct atxml__RegisterInstStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterInstStatus(struct soap*, struct atxml__RegisterInstStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterInstStatus(struct soap*, const struct atxml__RegisterInstStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterInstStatus(struct soap*, const char*, int, const struct atxml__RegisterInstStatus *, const char*);
SOAP_FMAC3 struct atxml__RegisterInstStatus * SOAP_FMAC4 soap_get_atxml__RegisterInstStatus(struct soap*, struct atxml__RegisterInstStatus *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterInstStatus * SOAP_FMAC4 soap_in_atxml__RegisterInstStatus(struct soap*, const char*, struct atxml__RegisterInstStatus *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterInstStatusResponse
#define SOAP_TYPE_atxml__RegisterInstStatusResponse (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterInstStatusResponse(struct soap*, const struct atxml__RegisterInstStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterInstStatusResponse(struct soap*, struct atxml__RegisterInstStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterInstStatusResponse(struct soap*, const struct atxml__RegisterInstStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterInstStatusResponse(struct soap*, const char*, int, const struct atxml__RegisterInstStatusResponse *, const char*);
SOAP_FMAC3 struct atxml__RegisterInstStatusResponse * SOAP_FMAC4 soap_get_atxml__RegisterInstStatusResponse(struct soap*, struct atxml__RegisterInstStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterInstStatusResponse * SOAP_FMAC4 soap_in_atxml__RegisterInstStatusResponse(struct soap*, const char*, struct atxml__RegisterInstStatusResponse *, const char*);

#ifndef SOAP_TYPE_atxml__TestStationStatus
#define SOAP_TYPE_atxml__TestStationStatus (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__TestStationStatus(struct soap*, const struct atxml__TestStationStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__TestStationStatus(struct soap*, struct atxml__TestStationStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__TestStationStatus(struct soap*, const struct atxml__TestStationStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__TestStationStatus(struct soap*, const char*, int, const struct atxml__TestStationStatus *, const char*);
SOAP_FMAC3 struct atxml__TestStationStatus * SOAP_FMAC4 soap_get_atxml__TestStationStatus(struct soap*, struct atxml__TestStationStatus *, const char*, const char*);
SOAP_FMAC3 struct atxml__TestStationStatus * SOAP_FMAC4 soap_in_atxml__TestStationStatus(struct soap*, const char*, struct atxml__TestStationStatus *, const char*);

#ifndef SOAP_TYPE_atxml__TestStationStatusResponse
#define SOAP_TYPE_atxml__TestStationStatusResponse (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__TestStationStatusResponse(struct soap*, const struct atxml__TestStationStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__TestStationStatusResponse(struct soap*, struct atxml__TestStationStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__TestStationStatusResponse(struct soap*, const struct atxml__TestStationStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__TestStationStatusResponse(struct soap*, const char*, int, const struct atxml__TestStationStatusResponse *, const char*);
SOAP_FMAC3 struct atxml__TestStationStatusResponse * SOAP_FMAC4 soap_get_atxml__TestStationStatusResponse(struct soap*, struct atxml__TestStationStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__TestStationStatusResponse * SOAP_FMAC4 soap_in_atxml__TestStationStatusResponse(struct soap*, const char*, struct atxml__TestStationStatusResponse *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterRemoveSequence
#define SOAP_TYPE_atxml__RegisterRemoveSequence (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterRemoveSequence(struct soap*, const struct atxml__RegisterRemoveSequence *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterRemoveSequence(struct soap*, struct atxml__RegisterRemoveSequence *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterRemoveSequence(struct soap*, const struct atxml__RegisterRemoveSequence *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterRemoveSequence(struct soap*, const char*, int, const struct atxml__RegisterRemoveSequence *, const char*);
SOAP_FMAC3 struct atxml__RegisterRemoveSequence * SOAP_FMAC4 soap_get_atxml__RegisterRemoveSequence(struct soap*, struct atxml__RegisterRemoveSequence *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterRemoveSequence * SOAP_FMAC4 soap_in_atxml__RegisterRemoveSequence(struct soap*, const char*, struct atxml__RegisterRemoveSequence *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterRemoveSequenceResponse
#define SOAP_TYPE_atxml__RegisterRemoveSequenceResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterRemoveSequenceResponse(struct soap*, const struct atxml__RegisterRemoveSequenceResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterRemoveSequenceResponse(struct soap*, struct atxml__RegisterRemoveSequenceResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterRemoveSequenceResponse(struct soap*, const struct atxml__RegisterRemoveSequenceResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterRemoveSequenceResponse(struct soap*, const char*, int, const struct atxml__RegisterRemoveSequenceResponse *, const char*);
SOAP_FMAC3 struct atxml__RegisterRemoveSequenceResponse * SOAP_FMAC4 soap_get_atxml__RegisterRemoveSequenceResponse(struct soap*, struct atxml__RegisterRemoveSequenceResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterRemoveSequenceResponse * SOAP_FMAC4 soap_in_atxml__RegisterRemoveSequenceResponse(struct soap*, const char*, struct atxml__RegisterRemoveSequenceResponse *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterApplySequence
#define SOAP_TYPE_atxml__RegisterApplySequence (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterApplySequence(struct soap*, const struct atxml__RegisterApplySequence *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterApplySequence(struct soap*, struct atxml__RegisterApplySequence *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterApplySequence(struct soap*, const struct atxml__RegisterApplySequence *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterApplySequence(struct soap*, const char*, int, const struct atxml__RegisterApplySequence *, const char*);
SOAP_FMAC3 struct atxml__RegisterApplySequence * SOAP_FMAC4 soap_get_atxml__RegisterApplySequence(struct soap*, struct atxml__RegisterApplySequence *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterApplySequence * SOAP_FMAC4 soap_in_atxml__RegisterApplySequence(struct soap*, const char*, struct atxml__RegisterApplySequence *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterApplySequenceResponse
#define SOAP_TYPE_atxml__RegisterApplySequenceResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterApplySequenceResponse(struct soap*, const struct atxml__RegisterApplySequenceResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterApplySequenceResponse(struct soap*, struct atxml__RegisterApplySequenceResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterApplySequenceResponse(struct soap*, const struct atxml__RegisterApplySequenceResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterApplySequenceResponse(struct soap*, const char*, int, const struct atxml__RegisterApplySequenceResponse *, const char*);
SOAP_FMAC3 struct atxml__RegisterApplySequenceResponse * SOAP_FMAC4 soap_get_atxml__RegisterApplySequenceResponse(struct soap*, struct atxml__RegisterApplySequenceResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterApplySequenceResponse * SOAP_FMAC4 soap_in_atxml__RegisterApplySequenceResponse(struct soap*, const char*, struct atxml__RegisterApplySequenceResponse *, const char*);

#ifndef SOAP_TYPE_atxml__ValidateRequirements
#define SOAP_TYPE_atxml__ValidateRequirements (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__ValidateRequirements(struct soap*, const struct atxml__ValidateRequirements *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__ValidateRequirements(struct soap*, struct atxml__ValidateRequirements *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__ValidateRequirements(struct soap*, const struct atxml__ValidateRequirements *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__ValidateRequirements(struct soap*, const char*, int, const struct atxml__ValidateRequirements *, const char*);
SOAP_FMAC3 struct atxml__ValidateRequirements * SOAP_FMAC4 soap_get_atxml__ValidateRequirements(struct soap*, struct atxml__ValidateRequirements *, const char*, const char*);
SOAP_FMAC3 struct atxml__ValidateRequirements * SOAP_FMAC4 soap_in_atxml__ValidateRequirements(struct soap*, const char*, struct atxml__ValidateRequirements *, const char*);

#ifndef SOAP_TYPE_atxml__ValidateRequirementsResponse
#define SOAP_TYPE_atxml__ValidateRequirementsResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__ValidateRequirementsResponse(struct soap*, const struct atxml__ValidateRequirementsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__ValidateRequirementsResponse(struct soap*, struct atxml__ValidateRequirementsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__ValidateRequirementsResponse(struct soap*, const struct atxml__ValidateRequirementsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__ValidateRequirementsResponse(struct soap*, const char*, int, const struct atxml__ValidateRequirementsResponse *, const char*);
SOAP_FMAC3 struct atxml__ValidateRequirementsResponse * SOAP_FMAC4 soap_get_atxml__ValidateRequirementsResponse(struct soap*, struct atxml__ValidateRequirementsResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__ValidateRequirementsResponse * SOAP_FMAC4 soap_in_atxml__ValidateRequirementsResponse(struct soap*, const char*, struct atxml__ValidateRequirementsResponse *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterTSF
#define SOAP_TYPE_atxml__RegisterTSF (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterTSF(struct soap*, const struct atxml__RegisterTSF *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterTSF(struct soap*, struct atxml__RegisterTSF *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterTSF(struct soap*, const struct atxml__RegisterTSF *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterTSF(struct soap*, const char*, int, const struct atxml__RegisterTSF *, const char*);
SOAP_FMAC3 struct atxml__RegisterTSF * SOAP_FMAC4 soap_get_atxml__RegisterTSF(struct soap*, struct atxml__RegisterTSF *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterTSF * SOAP_FMAC4 soap_in_atxml__RegisterTSF(struct soap*, const char*, struct atxml__RegisterTSF *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterTSFResponse
#define SOAP_TYPE_atxml__RegisterTSFResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterTSFResponse(struct soap*, const struct atxml__RegisterTSFResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterTSFResponse(struct soap*, struct atxml__RegisterTSFResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterTSFResponse(struct soap*, const struct atxml__RegisterTSFResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterTSFResponse(struct soap*, const char*, int, const struct atxml__RegisterTSFResponse *, const char*);
SOAP_FMAC3 struct atxml__RegisterTSFResponse * SOAP_FMAC4 soap_get_atxml__RegisterTSFResponse(struct soap*, struct atxml__RegisterTSFResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterTSFResponse * SOAP_FMAC4 soap_in_atxml__RegisterTSFResponse(struct soap*, const char*, struct atxml__RegisterTSFResponse *, const char*);

#ifndef SOAP_TYPE_atxml__RetrieveTpsData
#define SOAP_TYPE_atxml__RetrieveTpsData (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RetrieveTpsData(struct soap*, const struct atxml__RetrieveTpsData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RetrieveTpsData(struct soap*, struct atxml__RetrieveTpsData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RetrieveTpsData(struct soap*, const struct atxml__RetrieveTpsData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RetrieveTpsData(struct soap*, const char*, int, const struct atxml__RetrieveTpsData *, const char*);
SOAP_FMAC3 struct atxml__RetrieveTpsData * SOAP_FMAC4 soap_get_atxml__RetrieveTpsData(struct soap*, struct atxml__RetrieveTpsData *, const char*, const char*);
SOAP_FMAC3 struct atxml__RetrieveTpsData * SOAP_FMAC4 soap_in_atxml__RetrieveTpsData(struct soap*, const char*, struct atxml__RetrieveTpsData *, const char*);

#ifndef SOAP_TYPE_atxml__RetrieveTpsDataResponse
#define SOAP_TYPE_atxml__RetrieveTpsDataResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RetrieveTpsDataResponse(struct soap*, const struct atxml__RetrieveTpsDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RetrieveTpsDataResponse(struct soap*, struct atxml__RetrieveTpsDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RetrieveTpsDataResponse(struct soap*, const struct atxml__RetrieveTpsDataResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RetrieveTpsDataResponse(struct soap*, const char*, int, const struct atxml__RetrieveTpsDataResponse *, const char*);
SOAP_FMAC3 struct atxml__RetrieveTpsDataResponse * SOAP_FMAC4 soap_get_atxml__RetrieveTpsDataResponse(struct soap*, struct atxml__RetrieveTpsDataResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__RetrieveTpsDataResponse * SOAP_FMAC4 soap_in_atxml__RetrieveTpsDataResponse(struct soap*, const char*, struct atxml__RetrieveTpsDataResponse *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterInterUsed
#define SOAP_TYPE_atxml__RegisterInterUsed (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterInterUsed(struct soap*, const struct atxml__RegisterInterUsed *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterInterUsed(struct soap*, struct atxml__RegisterInterUsed *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterInterUsed(struct soap*, const struct atxml__RegisterInterUsed *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterInterUsed(struct soap*, const char*, int, const struct atxml__RegisterInterUsed *, const char*);
SOAP_FMAC3 struct atxml__RegisterInterUsed * SOAP_FMAC4 soap_get_atxml__RegisterInterUsed(struct soap*, struct atxml__RegisterInterUsed *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterInterUsed * SOAP_FMAC4 soap_in_atxml__RegisterInterUsed(struct soap*, const char*, struct atxml__RegisterInterUsed *, const char*);

#ifndef SOAP_TYPE_atxml__RegisterInterUsedResponse
#define SOAP_TYPE_atxml__RegisterInterUsedResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__RegisterInterUsedResponse(struct soap*, const struct atxml__RegisterInterUsedResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__RegisterInterUsedResponse(struct soap*, struct atxml__RegisterInterUsedResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__RegisterInterUsedResponse(struct soap*, const struct atxml__RegisterInterUsedResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__RegisterInterUsedResponse(struct soap*, const char*, int, const struct atxml__RegisterInterUsedResponse *, const char*);
SOAP_FMAC3 struct atxml__RegisterInterUsedResponse * SOAP_FMAC4 soap_get_atxml__RegisterInterUsedResponse(struct soap*, struct atxml__RegisterInterUsedResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__RegisterInterUsedResponse * SOAP_FMAC4 soap_in_atxml__RegisterInterUsedResponse(struct soap*, const char*, struct atxml__RegisterInterUsedResponse *, const char*);

#ifndef SOAP_TYPE_atxml__Close
#define SOAP_TYPE_atxml__Close (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__Close(struct soap*, const struct atxml__Close *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__Close(struct soap*, struct atxml__Close *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__Close(struct soap*, const struct atxml__Close *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__Close(struct soap*, const char*, int, const struct atxml__Close *, const char*);
SOAP_FMAC3 struct atxml__Close * SOAP_FMAC4 soap_get_atxml__Close(struct soap*, struct atxml__Close *, const char*, const char*);
SOAP_FMAC3 struct atxml__Close * SOAP_FMAC4 soap_in_atxml__Close(struct soap*, const char*, struct atxml__Close *, const char*);

#ifndef SOAP_TYPE_atxml__CloseResponse
#define SOAP_TYPE_atxml__CloseResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__CloseResponse(struct soap*, const struct atxml__CloseResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__CloseResponse(struct soap*, struct atxml__CloseResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__CloseResponse(struct soap*, const struct atxml__CloseResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__CloseResponse(struct soap*, const char*, int, const struct atxml__CloseResponse *, const char*);
SOAP_FMAC3 struct atxml__CloseResponse * SOAP_FMAC4 soap_get_atxml__CloseResponse(struct soap*, struct atxml__CloseResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__CloseResponse * SOAP_FMAC4 soap_in_atxml__CloseResponse(struct soap*, const char*, struct atxml__CloseResponse *, const char*);

#ifndef SOAP_TYPE_atxml__Initialize
#define SOAP_TYPE_atxml__Initialize (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__Initialize(struct soap*, const struct atxml__Initialize *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__Initialize(struct soap*, struct atxml__Initialize *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__Initialize(struct soap*, const struct atxml__Initialize *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__Initialize(struct soap*, const char*, int, const struct atxml__Initialize *, const char*);
SOAP_FMAC3 struct atxml__Initialize * SOAP_FMAC4 soap_get_atxml__Initialize(struct soap*, struct atxml__Initialize *, const char*, const char*);
SOAP_FMAC3 struct atxml__Initialize * SOAP_FMAC4 soap_in_atxml__Initialize(struct soap*, const char*, struct atxml__Initialize *, const char*);

#ifndef SOAP_TYPE_atxml__InitializeResponse
#define SOAP_TYPE_atxml__InitializeResponse (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_atxml__InitializeResponse(struct soap*, const struct atxml__InitializeResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_atxml__InitializeResponse(struct soap*, struct atxml__InitializeResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_atxml__InitializeResponse(struct soap*, const struct atxml__InitializeResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_atxml__InitializeResponse(struct soap*, const char*, int, const struct atxml__InitializeResponse *, const char*);
SOAP_FMAC3 struct atxml__InitializeResponse * SOAP_FMAC4 soap_get_atxml__InitializeResponse(struct soap*, struct atxml__InitializeResponse *, const char*, const char*);
SOAP_FMAC3 struct atxml__InitializeResponse * SOAP_FMAC4 soap_in_atxml__InitializeResponse(struct soap*, const char*, struct atxml__InitializeResponse *, const char*);

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (87)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
