#ifndef _LEXKEY_H_
#define _LEXKEY_H_
//
//	VERBS
//
enum enumTyxVerbs {
	V_APP       =   1, // apply
	V_ARM       =   2, // arm
	V_CAL       =   3, // calculate
	V_CHN       =   4, // change
	V_CLS       =   5, // close
	V_CMP       =   6, // compare
	V_CON       =   7, // connect
	V_CPL       =   8, // couple
	V_CRE       =   9, // create
	V_DCL       =  10, // declare
	V_DEF       =  11, // define
	V_DEL       =  12, // delete
	V_DIS       =  13, // disconnect
	V_DO        =  14, // do
	V_DSB       =  15, // disable
	V_ELS       =  16, // else
	V_ENB       =  17, // enable
	V_END       =  18, // end
	V_EST       =  19, // establish
	V_FIN       =  20, // finish
	V_FOR       =  21, // for
	V_FTH       =  22, // fetch
	V_GTO       =  23, // go to
	V_IDY       =  24, // identify
	V_IF        =  25, // if
	V_INC       =  26, // include
	V_INP       =  27, // input
	V_INX       =  28, // initiate
	V_LVE       =  29, // leave
	V_MEA       =  30, // measure
	V_MON       =  31, // monitor
	V_OPN       =  32, // open
	V_OUT       =  33, // output
	V_PFM       =  34, // perform
	V_PRV       =  35, // prove
	V_RD        =  36, // read
	V_REM       =  37, // remove
	V_REQ       =  38, // require
	V_RES       =  39, // resume
	V_RST       =  40, // reset
	V_SET       =  41, // setup
	V_SNS       =  42, // sense
	V_STI       =  43, // stimulate
	V_TRM       =  44, // terminate
	V_UCP       =  45, // uncouple
	V_UPD       =  46, // update
	V_VER       =  47, // verify
	V_WHL       =  48, // while
	V_WTF       =  49, // wait for
	V_XTN       =  50, // extend
	V__CNT      =  51, // symbol count
};
//
//	NOUNS
//
enum enumTyxNouns {
	N_ACS       =   1, // ac signal
	N_ADF       =   2, // adf
	N_AMB       =   3, // ambient conditions
	N_AMS       =   4, // am signal
	N_ATC       =   5, // atc
	N_BUS       =   6, // bus protocol
	N_BUT       =   7, // button
	N_CLX       =   8, // complex signal
	N_COM       =   9, // common
	N_DCF       =  10, // digital configuration
	N_DCS       =  11, // dc signal
	N_DGT       =  12, // digital test
	N_DIS       =  13, // displacement
	N_DME       =  14, // dme
	N_DOP       =  15, // doppler
	N_EAR       =  16, // earth
	N_EMF       =  17, // em field
	N_EPW       =  18, // exponential pulse wave
	N_EVS       =  19, // events
	N_EVT       =  20, // event
	N_EXC       =  21, // exchange
	N_FLU       =  22, // fluid signal
	N_FMS       =  23, // fm signal
	N_HEA       =  24, // heat
	N_IFF       =  25, // iff
	N_ILS       =  26, // ils
	N_IMP       =  27, // impedance
	N_INF       =  28, // infrared
	N_LAS       =  29, // laser
	N_LCL       =  30, // logic control
	N_LDT       =  31, // logic data
	N_LGT       =  32, // light
	N_LLD       =  33, // logic load
	N_LRF       =  34, // logic reference
	N_LTR       =  35, // laser target return
	N_MAN       =  36, // manometric
	N_MDS       =  37, // modulated signal
	N_MIF       =  38, // multi-sensor-infrared
	N_MIL       =  39, // multi-sensor-light
	N_PAC       =  40, // pulsed ac
	N_PAM       =  41, // pam
	N_PAT       =  42, // pulsed ac train
	N_PDC       =  43, // pulsed dc
	N_PDP       =  44, // pulsed doppler
	N_PDT       =  45, // pulsed dc train
	N_PMS       =  46, // pm signal
	N_RDN       =  47, // random noise
	N_RDS       =  48, // radar signal
	N_RPS       =  49, // ramp signal
	N_RSL       =  50, // resolver
	N_RTN       =  51, // rotation
	N_SCS       =  52, // sup car signal
	N_SHT       =  53, // short
	N_SIM       =  54, // simultaneous
	N_SIN       =  55, // sinc wave
	N_SQW       =  56, // square wave
	N_STM       =  57, // stepper motor
	N_STS       =  58, // step signal
	N_SYN       =  59, // synchro
	N_TAC       =  60, // tacan
	N_TDG       =  61, // timed digital
	N_TED       =  62, // turbine engine data
	N_TMI       =  63, // time interval
	N_TMR       =  64, // timer
	N_TRI       =  65, // triangular wave signal
	N_VBR       =  66, // vibration
	N_VID       =  67, // video signal
	N_VOR       =  68, // vor
	N_WAV       =  69, // waveform
	N__CNT      =  70, // symbol count
};
//
//	MODIFIERS
//
enum enumTyxModifiers {
	M_ACCF      =   1, // ac-comp-freq
	M_ACCP      =   2, // ac-comp
	M_ADFM      =   3, // add-from
	M_ADLN      =   4, // addr-lines
	M_ADTO      =   5, // add-to
	M_AGER      =   6, // age-rate
	M_ALLW      =   7, // allowance
	M_ALTI      =   8, // alt
	M_ALTR      =   9, // alt-rate
	M_AMBT      =  10, // ambient-temp
	M_AMCP      =  11, // am-comp
	M_AMCU      =  12, // am-coupl
	M_AMFQ      =  13, // am-freq
	M_AMMC      =  14, // ampl-mod-c
	M_AMMF      =  15, // ampl-mod-f
	M_AMPL      =  16, // ampl-mod
	M_AMSH      =  17, // am-shift
	M_AMSR      =  18, // am-source
	M_ANAC      =  19, // angle-accel
	M_ANAX      =  20, // angle-accel-x
	M_ANAY      =  21, // angle-accel-y
	M_ANAZ      =  22, // angle-accel-z
	M_ANGL      =  23, // angle
	M_ANGP      =  24, // angle-phi
	M_ANGT      =  25, // angle-theta
	M_ANGX      =  26, // angle-x
	M_ANGY      =  27, // angle-y
	M_ANGZ      =  28, // angle-z
	M_ANRT      =  29, // angle-rate
	M_ANRX      =  30, // angle-rate-x
	M_ANRY      =  31, // angle-rate-y
	M_ANRZ      =  32, // angle-rate-z
	M_ANSD      =  33, // ant-speed-dev
	M_ATMS      =  34, // atmos
	M_ATTE      =  35, // attenuation
	M_ATTN      =  36, // atten
	M_AUCO      =  37, // autocollimation-error
	M_BAND      =  38, // bandwidth
	M_BARP      =  39, // barometric-press
	M_BDTH      =  40, // beam-detection-threshold
	M_BITP      =  41, // bit-period
	M_BITR      =  42, // bit-rate
	M_BKPH      =  43, // back-porch
	M_BLKT      =  44, // blackbody-temp
	M_BRAN      =  45, // boresight-angle
	M_BTRN      =  46, // bit-transition
	M_BURD      =  47, // burst-droop
	M_BURR      =  48, // burst-rep-rate
	M_BURS      =  49, // burst
	M_BUSM      =  50, // bus-mode
	M_BUSS      =  51, // bus-spec
	M_CAMG      =  52, // camera-gain
	M_CAMP      =  53, // car-ampl
	M_CAPA      =  54, // cap
	M_CCOM      =  55, // count-command
	M_CDAT      =  56, // count-data
	M_CFRQ      =  57, // car-freq
	M_CHAN      =  58, // channel
	M_CHCT      =  59, // chan-crosstalk
	M_CHID      =  60, // channel-ident
	M_CHIT      =  61, // chan-integrity
	M_CHRM      =  62, // car-harmonics
	M_CLKS      =  63, // clock-source
	M_CMCH      =  64, // compare-ch
	M_CMDW      =  65, // command-word
	M_CMPL      =  66, // compl
	M_CMTO      =  67, // compare-to
	M_CMWB      =  68, // command-word-bit
	M_CMWV      =  69, // compare-wave
	M_COMD      =  70, // command
	M_COND      =  71, // conductance
	M_COUN      =  72, // count
	M_CPHS      =  73, // car-phase
	M_CPKN      =  74, // current-p-neg
	M_CPKP      =  75, // current-p-pos
	M_CPLG      =  76, // coupling
	M_CRSD      =  77, // car-resid
	M_CRSF      =  78, // crest-factor
	M_CSTS      =  79, // count-status
	M_CTRQ      =  80, // cutoff-freq
	M_CUPK      =  81, // current-p
	M_CUPP      =  82, // current-pp
	M_CUR0      =  83, // current-zero
	M_CUR1      =  84, // current-one
	M_CURA      =  85, // av-current
	M_CURI      =  86, // current-inst
	M_CURL      =  87, // current-lmt
	M_CURQ      =  88, // current-quies
	M_CURR      =  89, // current
	M_CURT      =  90, // current-trms
	M_CWLV      =  91, // cw-level
	M_DATA      =  92, // data
	M_DATL      =  93, // data-word-length
	M_DATP      =  94, // data-word-parity
	M_DATS      =  95, // data-word-sync
	M_DATT      =  96, // data-word-tr
	M_DATW      =  97, // data-word
	M_DBLI      =  98, // dbl-int
	M_DBND      =  99, // doppler-bandwidth
	M_DBRC      = 100, // debris-count
	M_DBRS      = 101, // debris-size
	M_DCOF      = 102, // dc-offset
	M_DDMD      = 103, // ddm
	M_DEEM      = 104, // de-emphasis
	M_DELA      = 105, // delay
	M_DEST      = 106, // destination
	M_DEWP      = 107, // dewpoint
	M_DFBA      = 108, // diff-boresight-angle
	M_DIFR      = 109, // differentiate
	M_DIFT      = 110, // differential-temp
	M_DIGS      = 111, // dig-spec
	M_DISP      = 112, // display
	M_DIST      = 113, // distance
	M_DIVG      = 114, // divergence
	M_DIVS      = 115, // divisions
	M_DMDS      = 116, // dominant-mod-sig
	M_DPFR      = 117, // doppler-freq
	M_DPSH      = 118, // doppler-shift
	M_DROO      = 119, // droop
	M_DSFC      = 120, // diss-factor
	M_DSTR      = 121, // distance-r
	M_DSTX      = 122, // distance-x
	M_DSTY      = 123, // distance-y
	M_DSTZ      = 124, // distance-z
	M_DTCT      = 125, // detector-count
	M_DTER      = 126, // diff-temp-error
	M_DTIL      = 127, // diff-temp-interval
	M_DTMD      = 128, // do-timed-digital
	M_DTOR      = 129, // distortion
	M_DTSC      = 130, // detector-scan
	M_DTSP      = 131, // diff-temp-stop
	M_DTST      = 132, // diff-temp-start
	M_DUTY      = 133, // duty-cycle
	M_DVPN      = 134, // dev-pneg
	M_DVPP      = 135, // dev-ppos
	M_DWBT      = 136, // data-word-bit
	M_DYRA      = 137, // dynamic-range
	M_EDLN      = 138, // end-line
	M_EDUT      = 139, // end-unit
	M_EFCY      = 140, // efficacy
	M_EFFI      = 141, // eff
	M_EGDR      = 142, // energy-distribution
	M_EINM      = 143, // event-interval
	M_ERRI      = 144, // error-index
	M_ERRO      = 145, // error
	M_EVAO      = 146, // event-after-occurrences
	M_EVDL      = 147, // event-delay
	M_EVEO      = 148, // event-each-occurrence
	M_EVEV      = 149, // event-every
	M_EVFO      = 150, // event-first-occurrence
	M_EVGB      = 151, // event-gated-by
	M_EVGF      = 152, // event-gate-from
	M_EVGR      = 153, // event-gate-forever
	M_EVGT      = 154, // event-gate-to
	M_EVOU      = 155, // event-out
	M_EVSB      = 156, // event-sync-bit
	M_EVSF      = 157, // event-sync-freq
	M_EVSL      = 158, // event-slope
	M_EVSW      = 159, // event-sync-word
	M_EVTF      = 160, // event-time-from
	M_EVTI      = 161, // event-indicator
	M_EVTR      = 162, // event-time-forever
	M_EVTT      = 163, // event-time-to
	M_EVUN      = 164, // event-until
	M_EVWH      = 165, // event-when
	M_EVXE      = 166, // event-sense
	M_EVXM      = 167, // event-stim
	M_EXAE      = 168, // except at every
	M_EXNM      = 169, // exchange-number
	M_EXPO      = 170, // exponent
	M_FALL      = 171, // fall-time
	M_FCLN      = 172, // focal-length
	M_FCNT      = 173, // frame-count
	M_FDST      = 174, // field-strength
	M_FDVW      = 175, // field-of-view
	M_FIAL      = 176, // first-active-line
	M_FILT      = 177, // filter
	M_FLTC      = 178, // fault-count
	M_FLTS      = 179, // fault-test
	M_FLUT      = 180, // fluid-type
	M_FMCP      = 181, // fm-comp
	M_FMCU      = 182, // fm-coupl
	M_FMFQ      = 183, // fm-freq
	M_FMSR      = 184, // fm-source
	M_FRCE      = 185, // force
	M_FRCR      = 186, // force-rate
	M_FREQ      = 187, // freq
	M_FRMT      = 188, // format
	M_FRQ0      = 189, // freq-zero
	M_FRQ1      = 190, // freq-one
	M_FRQD      = 191, // freq-dev
	M_FRQP      = 192, // freq-pairing
	M_FRQQ      = 193, // freq-quies
	M_FRQR      = 194, // freq-ratio
	M_FRQW      = 195, // freq-window
	M_FUEL      = 196, // fuel-supply
	M_FXDN      = 197, // flux-dens
	M_FXIP      = 198, // flux-dens-in-phase
	M_FXQD      = 199, // flux-dens-quad
	M_GAMA      = 200, // gamma
	M_GSLP      = 201, // glide-slope
	M_GSRE      = 202, // gray-scale-resolution
	M_HAPW      = 203, // harm-power
	M_HARM      = 204, // harmonics
	M_HARN      = 205, // harm-number
	M_HARP      = 206, // harm-phase
	M_HARV      = 207, // harm-voltage
	M_HFOV      = 208, // h-field-of-view
	M_HIZZ      = 209, // hiz
	M_HLAE      = 210, // h-los-align-error
	M_HMDF      = 211, // hi-mod-freq
	M_HRAG      = 212, // h-reference-angle
	M_HSRM      = 213, // h-sensor-resolution-min
	M_HTAG      = 214, // h-target-angle
	M_HTOF      = 215, // h-target-offset
	M_HUMY      = 216, // humidity
	M_IASP      = 217, // ias
	M_ICWB      = 218, // invalid-command-word-bit
	M_IDSE      = 219, // ident-sig-ep
	M_IDSF      = 220, // ident-sig-freq
	M_IDSG      = 221, // ident-sig
	M_IDSM      = 222, // ident-sig-mod
	M_IDWB      = 223, // invalid-data-word-bit
	M_IJIT      = 224, // int-jitter
	M_ILLU      = 225, // illum
	M_INDU      = 226, // ind
	M_INTG      = 227, // integrate
	M_INTL      = 228, // interval
	M_IRAT      = 229, // int-rate
	M_ISTI      = 230, // illegal-state-indicator
	M_ISWB      = 231, // invalid-status-word-bit
	M_ITER      = 232, // iterate
	M_ITRO      = 233, // intensity-ratio
	M_IVCW      = 234, // invalid-command-word
	M_IVDL      = 235, // invalid-data-word-length
	M_IVDP      = 236, // invalid-data-word-parity
	M_IVDS      = 237, // invalid-data-word-sync
	M_IVDT      = 238, // invalid-data-word-tr
	M_IVDW      = 239, // invalid-data-word
	M_IVMG      = 240, // invalid-message-gap
	M_IVOA      = 241, // invalid-one-amplitude
	M_IVRT      = 242, // invalid-response-time
	M_IVSW      = 243, // invalid-status-word
	M_IVWC      = 244, // invalid-word-count
	M_IVWG      = 245, // invalid-word-gap
	M_IVWL      = 246, // invalid-word-length
	M_IVZA      = 247, // invalid-zero-amplitude
	M_IVZC      = 248, // invalid-zero-crossing
	M_LDFM      = 249, // load-from
	M_LDTO      = 250, // load-to
	M_LDVW      = 251, // load-wave
	M_LINE      = 252, // line
	M_LIPF      = 253, // lines-per-channel
	M_LMDF      = 254, // lo-mod-freq
	M_LMIN      = 255, // lum-int
	M_LOCL      = 256, // localizer
	M_LRAN      = 257, // lst-reference-angle
	M_LSAE      = 258, // los-align-error
	M_LSTG      = 259, // laser-stage
	M_LUMF      = 260, // lum-flux
	M_LUMI      = 261, // luminance
	M_LUMT      = 262, // lum-temp
	M_LVLO      = 263, // level-logic-one
	M_LVLZ      = 264, // level-logic-zero
	M_MAGB      = 265, // mag-bearing
	M_MAGR      = 266, // mag-bearing-rate
	M_MAMP      = 267, // mod-ampl
	M_MANI      = 268, // manual-intervention
	M_MASF      = 269, // mass-flow
	M_MASK      = 270, // mask-one
	M_MATH      = 271, // math
	M_MAXT      = 272, // max-time
	M_MBAT      = 273, // main-beam-atten
	M_MDPN      = 274, // mod-pneg
	M_MDPP      = 275, // mod-ppos
	M_MDSC      = 276, // mod-source
	M_MGAP      = 277, // message-gap
	M_MMOD      = 278, // mean-mod
	M_MODD      = 279, // mod-dist
	M_MODE      = 280, // mode
	M_MODF      = 281, // mod-freq
	M_MODO      = 282, // mod-offset
	M_MODP      = 283, // mod-phase
	M_MPFM      = 284, // multp-from
	M_MPTO      = 285, // multp-to
	M_MRCO      = 286, // min-resolv-contrast
	M_MRKB      = 287, // marker-beacon
	M_MRTD      = 288, // min-resolv-temp-diff
	M_MSKZ      = 289, // mask-zero
	M_MSNR      = 290, // minimum-sense-rate
	M_MTFD      = 291, // mtf-direction
	M_MTFP      = 292, // mtf-freq-points
	M_MTFU      = 293, // modulation-transfer-function
	M_NEDT      = 294, // noise-eq-diff-temp
	M_NEGS      = 295, // neg-slope
	M_NHAR      = 296, // non-harmonics
	M_NLIN      = 297, // non-lin
	M_NOAD      = 298, // noise-ampl-dens
	M_NOAV      = 299, // noise-av
	M_NOIS      = 300, // noise
	M_NOPD      = 301, // noise-pwr-dens
	M_NOPK      = 302, // noise-p
	M_NOPP      = 303, // noise-pp
	M_NOTR      = 304, // noise-trms
	M_NPWT      = 305, // neg-pulse-width
	M_OAMP      = 306, // one-amplitude
	M_OTMP      = 307, // oper-temp
	M_OVER      = 308, // overshoot
	M_P3DV      = 309, // p3-dev
	M_P3LV      = 310, // p3-level
	M_PAMP      = 311, // p-ampl
	M_PANG      = 312, // phase-angle
	M_PARE      = 313, // parity-even
	M_PARO      = 314, // parity-odd
	M_PAST      = 315, // pulse-ampl-stab
	M_PATH      = 316, // path
	M_PATN      = 317, // pulse-atten
	M_PATT      = 318, // pattern
	M_PCCU      = 319, // pac-coupl
	M_PCLS      = 320, // pulse-class
	M_PCSR      = 321, // pac-source
	M_PDEV      = 322, // phase-dev
	M_PDGN      = 323, // peak-degen
	M_PDRP      = 324, // pair-droop
	M_PDVN      = 325, // phase-dev-pn
	M_PDVP      = 326, // phase-dev-pp
	M_PERI      = 327, // period
	M_PEST      = 328, // pulse-energy-stab
	M_PHPN      = 329, // phase-pneg
	M_PHPP      = 330, // phase-ppos
	M_PJIT      = 331, // phase-jit
	M_PKDV      = 332, // peak-dev
	M_PLAN      = 333, // pla
	M_PLAR      = 334, // pla-rate
	M_PLEG      = 335, // pulse-energy
	M_PLID      = 336, // pulse-ident
	M_PLSE      = 337, // pulses-excl
	M_PLSI      = 338, // pulses-incl
	M_PLWD      = 339, // pulse-width
	M_PMCU      = 340, // pm-coupl
	M_PMFQ      = 341, // pm-freq
	M_PMSR      = 342, // pm-source
	M_PODN      = 343, // power-dens
	M_POSI      = 344, // position
	M_POSS      = 345, // pos-slope
	M_POWA      = 346, // power-av
	M_POWP      = 347, // power-p
	M_POWR      = 348, // power
	M_PPOS      = 349, // pulse-posn
	M_PPST      = 350, // pulse-period-stab
	M_PPWT      = 351, // pos-pulse-width
	M_PRCD      = 352, // proceed
	M_PRDF      = 353, // power-diff
	M_PRFR      = 354, // prf
	M_PRIO      = 355, // priority
	M_PROA      = 356, // press-osc-ampl
	M_PROF      = 357, // press-osc-freq
	M_PRSA      = 358, // press-a
	M_PRSG      = 359, // press-g
	M_PRSR      = 360, // press-rate
	M_PRTY      = 361, // parity
	M_PSHI      = 362, // phase-shift
	M_PSHT      = 363, // preshoot
	M_PSPC      = 364, // pair-spacing
	M_PSPE      = 365, // pulse-spect
	M_PSPT      = 366, // pulse-spect-threshold
	M_PSRC      = 367, // peak-search
	M_PTCP      = 368, // tcp
	M_PUDP      = 369, // udp
	M_PWRL      = 370, // pwr-lmt
	M_QFAC      = 371, // q
	M_QUAD      = 372, // quad
	M_RADL      = 373, // radial
	M_RADR      = 374, // radial-rate
	M_RAIL      = 375, // radiance-interval
	M_RASP      = 376, // radiance-stop
	M_RAST      = 377, // radiance-start
	M_RCVS      = 378, // receiver-sensitivity
	M_RDNC      = 379, // radiance
	M_REAC      = 380, // reactance
	M_REFF      = 381, // ref-freq
	M_REFI      = 382, // ref-inertial
	M_REFM      = 383, // reference-mirror-size
	M_REFP      = 384, // ref-power
	M_REFR      = 385, // ref-res
	M_REFS      = 386, // ref-source
	M_REFU      = 387, // ref-uut
	M_REFV      = 388, // ref-volt
	M_REFX      = 389, // ref
	M_RELB      = 390, // rel-bearing
	M_RELH      = 391, // relative-humidity
	M_RELW      = 392, // relative-wind
	M_REPT      = 393, // repeat
	M_RERR      = 394, // range-error
	M_RESB      = 395, // resolution-bandwidth
	M_RESI      = 396, // res
	M_RESP      = 397, // resp
	M_RESR      = 398, // res-ratio
	M_RING      = 399, // ringing
	M_RISE      = 400, // rise-time
	M_RLBR      = 401, // rel-bearing-rate
	M_RLVL      = 402, // radiance-level-count
	M_RMNS      = 403, // ramp-neg-slope
	M_RMOD      = 404, // ranging-mode
	M_RMPS      = 405, // ramp-pos-slope
	M_ROUN      = 406, // rounding
	M_RPDV      = 407, // range-pulse-dev
	M_RPEC      = 408, // range-pulse-echo
	M_RPHF      = 409, // ref-phase-freq
	M_RPLD      = 410, // ref-pulses-dev
	M_RPLE      = 411, // reply-eff
	M_RPLI      = 412, // ref-pulses-incl
	M_RPLX      = 413, // ref-pulses-excl
	M_RSPH      = 414, // resp-hiz
	M_RSPO      = 415, // resp-one
	M_RSPT      = 416, // response-time
	M_RSPZ      = 417, // resp-zero
	M_RTRS      = 418, // rotor-speed
	M_SASP      = 419, // sample-spacing
	M_SATM      = 420, // sample-time
	M_SBAT      = 421, // satellite-beam-atten
	M_SBCF      = 422, // sub-car-freq
	M_SBCM      = 423, // sub-car-mod
	M_SBEV      = 424, // strobe-to-event
	M_SBFM      = 425, // subtract-from
	M_SBTO      = 426, // subtract-to
	M_SCNT      = 427, // sample-count
	M_SDEL      = 428, // sense-delay
	M_SERL      = 429, // serial-lsb-first
	M_SERM      = 430, // serial-msb-first
	M_SESA      = 431, // sensor-aperture
	M_SETT      = 432, // settle-time
	M_SGNO      = 433, // sig-noise
	M_SGTF      = 434, // sig-transfer-function
	M_SHFS      = 435, // shaft-speed
	M_SIMU      = 436, // do-simultaneous
	M_SITF      = 437, // sys-intens-transfer-function
	M_SKEW      = 438, // skew-time
	M_SLEW      = 439, // slew-rate
	M_SLRA      = 440, // slant-range-accel
	M_SLRG      = 441, // slant-range
	M_SLRR      = 442, // slant-range-rate
	M_SLSD      = 443, // sls-dev
	M_SLSL      = 444, // sls-level
	M_SMAV      = 445, // sample-av
	M_SMPL      = 446, // sample
	M_SMPW      = 447, // sample-width
	M_SMTH      = 448, // smooth
	M_SNAD      = 449, // sinad
	M_SNSR      = 450, // sense-rate
	M_SPCG      = 451, // spacing
	M_SPED      = 452, // speed
	M_SPGR      = 453, // spec-grav
	M_SPRT      = 454, // speed-ratio
	M_SPTM      = 455, // spec-temp
	M_SQD1      = 456, // sqtr-dist-1
	M_SQD2      = 457, // sqtr-dist-2
	M_SQD3      = 458, // sqtr-dist-3
	M_SQTD      = 459, // sqtr-dist
	M_SQTR      = 460, // sqtr-rate
	M_SRFR      = 461, // sensor-freq
	M_SSMD      = 462, // sensitivity-mode
	M_STAT      = 463, // status
	M_STBM      = 464, // satellite-beam
	M_STIM      = 465, // stim
	M_STLN      = 466, // start-line
	M_STMH      = 467, // stim-hiz
	M_STMO      = 468, // stim-one
	M_STMP      = 469, // static-temp
	M_STMR      = 470, // stim-rate
	M_STMZ      = 471, // stim-zero
	M_STOP      = 472, // stop
	M_STPA      = 473, // static-press-a
	M_STPB      = 474, // stop-bits
	M_STPG      = 475, // static-press-g
	M_STPR      = 476, // static-press-rate
	M_STPT      = 477, // set-of-points
	M_STRD      = 478, // standard
	M_STRT      = 479, // start
	M_STUT      = 480, // start-unit
	M_STWD      = 481, // status-word
	M_SUSP      = 482, // susceptance
	M_SVCP      = 483, // save-comp
	M_SVFM      = 484, // save-from
	M_SVTO      = 485, // save-to
	M_SVWV      = 486, // save-wave
	M_SWBT      = 487, // status-word-bit
	M_SWPT      = 488, // sweep-time
	M_SWRA      = 489, // swr
	M_SYDL      = 490, // sync-delay
	M_SYEV      = 491, // sync-to-event
	M_SYNC      = 492, // sync
	M_TASP      = 493, // tas
	M_TASY      = 494, // time-asym
	M_TCAP      = 495, // temp-coeff-cap
	M_TCBT      = 496, // tgt-coordinate-bottom
	M_TCLT      = 497, // tgt-coordinate-left
	M_TCRT      = 498, // tgt-coordinate-right
	M_TCTP      = 499, // tgt-coordinate-top
	M_TCUR      = 500, // temp-coeff-current
	M_TDAT      = 501, // target-data
	M_TEFC      = 502, // test-freq-count
	M_TEMP      = 503, // temp
	M_TEQL      = 504, // test-equip-listener
	M_TEQT      = 505, // test-equip-talker
	M_TERM      = 506, // terminated
	M_TGMD      = 507, // trigger-mode
	M_TGPL      = 508, // target-polarity
	M_TGTA      = 509, // target-range-accel
	M_TGTD      = 510, // target-range
	M_TGTH      = 511, // target-threshold
	M_TGTP      = 512, // target-type
	M_TGTR      = 513, // target-range-rate
	M_TGTS      = 514, // last-pulse-range
	M_THRT      = 515, // thrust
	M_TIEV      = 516, // time-every
	M_TILT      = 517, // tilt
	M_TIME      = 518, // time
	M_TIMP      = 519, // test-equip-imp
	M_TIND      = 520, // temp-coeff-ind
	M_TIUN      = 521, // time-until
	M_TIWH      = 522, // time-when
	M_TJIT      = 523, // time-jit
	M_TLAX      = 524, // tilt-axis
	M_TMON      = 525, // test-equip-monitor
	M_TOPA      = 526, // total-press-a
	M_TOPG      = 527, // total-press-g
	M_TOPR      = 528, // total-press-rate
	M_TORQ      = 529, // torque
	M_TPHD      = 530, // three-phase-delta
	M_TPHY      = 531, // three-phase-wye
	M_TREA      = 532, // temp-coeff-react
	M_TRES      = 533, // temp-coeff-res
	M_TRGS      = 534, // trig-source
	M_TRIG      = 535, // trig
	M_TRLV      = 536, // trig-level
	M_TRN0      = 537, // trans-zero
	M_TRN1      = 538, // trans-one
	M_TRNP      = 539, // trans-period
	M_TRNS      = 540, // trans-sync
	M_TROL      = 541, // test-equip-role
	M_TRSL      = 542, // trig-slope
	M_TRUE      = 543, // true
	M_TRUN      = 544, // timer-until
	M_TRWH      = 545, // timer-when
	M_TSAC      = 546, // test-area-count
	M_TSCC      = 547, // test-chan-count
	M_TSIM      = 548, // test-equip-simulate
	M_TSPC      = 549, // test-point-count
	M_TSTF      = 550, // test-field
	M_TTMP      = 551, // total-temp
	M_TVOL      = 552, // temp-coeff-volt
	M_TYPE      = 553, // type
	M_UNDR      = 554, // undershoot
	M_UNFY      = 555, // uniformity
	M_UNIT      = 556, // unit
	M_UUPL      = 557, // units-per-line
	M_UUTL      = 558, // uut-listener
	M_UUTT      = 559, // uut-talker
	M_VALU      = 560, // value
	M_VBAC      = 561, // vibration-accel
	M_VBAN      = 562, // video-bandwidth
	M_VBAP      = 563, // vibration-ampl-p
	M_VBPP      = 564, // vibration-ampl-pp
	M_VBRT      = 565, // vibration-rate
	M_VBTR      = 566, // vibration-ampl-trms
	M_VDIV      = 567, // volt-per-div
	M_VEAO      = 568, // event-after-occurrences-value
	M_VEDL      = 569, // event-delay-value
	M_VEEO      = 570, // event-each-occurrence-value
	M_VEFO      = 571, // event-first-occurrence-value
	M_VEGF      = 572, // event-gate-for
	M_VETF      = 573, // event-time-for
	M_VFOV      = 574, // v-field-of-view
	M_VINS      = 575, // voltage-inst
	M_VIST      = 576, // video-sync-type
	M_VLAE      = 577, // v-los-align-error
	M_VLAV      = 578, // av-voltage
	M_VLPK      = 579, // voltage-p
	M_VLPP      = 580, // voltage-pp
	M_VLT0      = 581, // voltage-zero
	M_VLT1      = 582, // voltage-one
	M_VLTL      = 583, // volt-lmt
	M_VLTQ      = 584, // voltage-quies
	M_VLTR      = 585, // voltage-ramped
	M_VLTS      = 586, // voltage-stepped
	M_VOLF      = 587, // volume-flow
	M_VOLR      = 588, // voltage-ratio
	M_VOLT      = 589, // voltage
	M_VPHF      = 590, // var-phase-freq
	M_VPHM      = 591, // var-phase-mod
	M_VPKN      = 592, // voltage-p-neg
	M_VPKP      = 593, // voltage-p-pos
	M_VRAG      = 594, // v-reference-angle
	M_VRMS      = 595, // voltage-trms
	M_VSRM      = 596, // v-sensor-resolution-min
	M_VTAG      = 597, // v-target-angle
	M_VTOF      = 598, // v-target-offset
	M_WAIT      = 599, // wait
	M_WAVE      = 600, // wave-length
	M_WDLN      = 601, // word-length
	M_WDRT      = 602, // word-rate
	M_WGAP      = 603, // word-gap
	M_WILD      = 604, // wild
	M_WIND      = 605, // wind-speed
	M_WRDC      = 606, // word-count
	M_WTRN      = 607, // word-transition
	M_XACE      = 608, // x-autocollimation-error
	M_XAGR      = 609, // x-angle-of-regard
	M_XBAG      = 610, // x-boresight-angle
	M_XTAR      = 611, // x-target-angle
	M_YACE      = 612, // y-autocollimation-error
	M_YAGR      = 613, // y-angle-of-regard
	M_YBAG      = 614, // y-boresight-angle
	M_YTAR      = 615, // y-target-angle
	M_ZAMP      = 616, // zero-amplitude
	M_ZCRS      = 617, // zero-crossing
	M_ZERO      = 618, // zero-index
	M__CNT      = 619, // symbol count
};
//
//	MODULETYPES
//
enum enumTyxModuletypes {
	T_ACS       =   1, // name not available
	T_API       =   2, // name not available
	T_ARB       =   3, // name not available
	T_ASA       =   4, // name not available
	T_DCS       =   5, // name not available
	T_DIG       =   6, // name not available
	T_DMM       =   7, // name not available
	T_DWG       =   8, // name not available
	T_FNG       =   9, // name not available
	T_FTM       =  10, // name not available
	T_MBT       =  11, // name not available
	T_MFU       =  12, // name not available
	T_MTR       =  13, // name not available
	T_PAT       =  14, // name not available
	T_PCM       =  15, // name not available
	T_PLG       =  16, // name not available
	T_PSS       =  17, // name not available
	T_PWM       =  18, // name not available
	T_QAL       =  19, // name not available
	T_RSV       =  20, // name not available
	T_RSY       =  21, // name not available
	T_SNG       =  22, // name not available
	T_SRS       =  23, // name not available
	T_VDG       =  24, // name not available
	T__CNT      =  25, // symbol count
};
//
//	DIMS-A
//
enum enumTyxDimsA {
	D_1553A     =   1, // mil-1553a
	D_1553B     =   2, // mil-1553b
	D_AFAPD     =   3, // afapd
	D_ALLLS     =   4, // all-listener
	D_AMI       =   5, // ami
	D_AR429     =   6, // arinc-429
	D_ARDC      =   7, // ardc
	D_BIP       =   8, // bip
	D_CANA      =   9, // cana
	D_CANB      =  10, // canb
	D_CDDI      =  11, // cddi
	D_CONMD     =  12, // con-mode
	D_CONRT     =  13, // con-rt
	D_CSM       =  14, // csm
	D_CSN       =  15, // csn
	D_CSOC      =  16, // consecutive-occurrences
	D_ETHERNET  =  17, // ethernet
	D_EVEN      =  18, // even
	D_HDB       =  19, // hdb
	D_ICAN      =  20, // ican
	D_ICAO      =  21, // icao
	D_IDL       =  22, // idl
	D_IEEE488   =  23, // ieee-488
	D_LNGTH     =  24, // length
	D_MARK      =  25, // mark
	D_MASTR     =  26, // master
	D_MIC       =  27, // mic
	D_MIP       =  28, // mip
	D_MONTR     =  29, // monitor
	D_MTS       =  30, // mts
	D_NONE      =  31, // none
	D_NRZ       =  32, // nrz
	D_ODD       =  33, // odd
	D_OFF       =  34, // off
	D_ON        =  35, // on
	D_PARA      =  36, // parallel
	D_PRIM      =  37, // primary
	D_PRTY      =  38, // parity
	D_REDT      =  39, // redundant
	D_RS232     =  40, // rs-232
	D_RS422     =  41, // rs-422
	D_RS485     =  42, // rs-485
	D_RTCON     =  43, // rt-con
	D_RTRT      =  44, // rt-rt
	D_RZ        =  45, // rz
	D_SERL      =  46, // serial-lsb-first
	D_SERM      =  47, // serial-msb-first
	D_SLAVE     =  48, // slave
	D_SYNC      =  49, // sync
	D_TACFIRE   =  50, // tacfire
	D_TLKLS     =  51, // talker-listener
	D_TR        =  52, // t-r
	D_WADC      =  53, // wadc
	D__CNT      =  54, // symbol count
};
//
//	DIMS-B
//
enum enumTyxDimsB {
	R__CNT      =   1, // symbol count
};
#endif // _LEXKEY_H_
