#define FNC_DIGITAL_CONFIG					01
#define FNC_STIM_STATIC_LOGIC_DATA			10
#define FNC_SENS_STATIC_LOGIC_DATA			17
#define FNC_PROV_STATIC_LOGIC_DATA			22
#define FNC_APLY_STATIC_LOGIC_DATA_DS		11
#define FNC_MEAS_STATIC_LOGIC_DATA_DS		12
#define FNC_APLY_STATIC_LOGIC_DATA_SCAN		31
#define FNC_MEAS_STATIC_LOGIC_DATA_SCAN		32

#define FNC_EVNT_EBE_CALL_TBE_SBE_2			51
#define FNC_EVNT_EBE_CALL_EBE				52
#define FNC_EVNT_EBE_CALL_TBE_SBE_3			53
#define FNC_EVNT_TBE_2						62
#define FNC_EVNT_SBE_2						72
#define FNC_EVNT_TBE_3						63
#define FNC_EVNT_SBE_3						73

#define FNC_TIMER							80
