#ifndef _LEXKEY_H_
#define _LEXKEY_H_
//
//	VERBS
//
enum enumTyxVerbs {
	V_APP       =   1, // apply
	V_ARM       =   2, // arm
	V_CAL       =   3, // calculate
	V_CHN       =   4, // change
	V_CLS       =   5, // close
	V_CMP       =   6, // compare
	V_CON       =   7, // connect
	V_CPL       =   8, // couple
	V_CRE       =   9, // create
	V_DCL       =  10, // declare
	V_DEF       =  11, // define
	V_DEL       =  12, // delete
	V_DIS       =  13, // disconnect
	V_DO        =  14, // do
	V_DSB       =  15, // disable
	V_ELS       =  16, // else
	V_ENB       =  17, // enable
	V_END       =  18, // end
	V_EST       =  19, // establish
	V_FIN       =  20, // finish
	V_FOR       =  21, // for
	V_FTH       =  22, // fetch
	V_GTO       =  23, // go to
	V_IDY       =  24, // identify
	V_IF        =  25, // if
	V_INC       =  26, // include
	V_INP       =  27, // input
	V_INX       =  28, // initiate
	V_LVE       =  29, // leave
	V_MEA       =  30, // measure
	V_MON       =  31, // monitor
	V_OPN       =  32, // open
	V_OUT       =  33, // output
	V_PFM       =  34, // perform
	V_PRV       =  35, // prove
	V_RD        =  36, // read
	V_REM       =  37, // remove
	V_REQ       =  38, // require
	V_RES       =  39, // resume
	V_RST       =  40, // reset
	V_SET       =  41, // setup
	V_SNS       =  42, // sense
	V_STI       =  43, // stimulate
	V_TRM       =  44, // terminate
	V_UCP       =  45, // uncouple
	V_UPD       =  46, // update
	V_VER       =  47, // verify
	V_WHL       =  48, // while
	V_WTF       =  49, // wait for
	V_XTN       =  50, // extend
	V__CNT      =  51, // symbol count
};
//
//	NOUNS
//
enum enumTyxNouns {
	N_ACS       =   1, // ac signal
	N_ADF       =   2, // adf
	N_AMB       =   3, // ambient conditions
	N_AMS       =   4, // am signal
	N_ATC       =   5, // atc
	N_BUS       =   6, // bus protocol
	N_BUT       =   7, // button
	N_COM       =   8, // common
	N_DCF       =   9, // digital configuration
	N_DCS       =  10, // dc signal
	N_DGT       =  11, // digital test
	N_DIS       =  12, // displacement
	N_DME       =  13, // dme
	N_DOP       =  14, // doppler
	N_EAR       =  15, // earth
	N_EMF       =  16, // em field
	N_EPW       =  17, // exponential pulse wave
	N_EVS       =  18, // events
	N_EVT       =  19, // event
	N_EXC       =  20, // exchange
	N_FLU       =  21, // fluid signal
	N_FMS       =  22, // fm signal
	N_HEA       =  23, // heat
	N_IFF       =  24, // iff
	N_ILS       =  25, // ils
	N_IMP       =  26, // impedance
	N_INF       =  27, // infrared
	N_LAS       =  28, // laser
	N_LCL       =  29, // logic control
	N_LDT       =  30, // logic data
	N_LGT       =  31, // light
	N_LLD       =  32, // logic load
	N_LRF       =  33, // logic reference
	N_LTR       =  34, // laser target return
	N_MAN       =  35, // manometric
	N_MDS       =  36, // modulated signal
	N_MIF       =  37, // multi-sensor-infrared
	N_MIL       =  38, // multi-sensor-light
	N_PAC       =  39, // pulsed ac
	N_PAM       =  40, // pam
	N_PAT       =  41, // pulsed ac train
	N_PDC       =  42, // pulsed dc
	N_PDP       =  43, // pulsed doppler
	N_PDT       =  44, // pulsed dc train
	N_PMS       =  45, // pm signal
	N_RDN       =  46, // random noise
	N_RDS       =  47, // radar signal
	N_RPS       =  48, // ramp signal
	N_RSL       =  49, // resolver
	N_RTN       =  50, // rotation
	N_SCS       =  51, // sup car signal
	N_SHT       =  52, // short
	N_SIM       =  53, // simultaneous
	N_SIN       =  54, // sinc wave
	N_SQW       =  55, // square wave
	N_STM       =  56, // stepper motor
	N_STS       =  57, // step signal
	N_SYN       =  58, // synchro
	N_TAC       =  59, // tacan
	N_TDG       =  60, // timed digital
	N_TED       =  61, // turbine engine data
	N_TMI       =  62, // time interval
	N_TMR       =  63, // timer
	N_TRI       =  64, // triangular wave signal
	N_VBR       =  65, // vibration
	N_VID       =  66, // video signal
	N_VOR       =  67, // vor
	N_WAV       =  68, // waveform
	N__CNT      =  69, // symbol count
};
//
//	MODIFIERS
//
enum enumTyxModifiers {
	M_ACCF      =   1, // ac-comp-freq
	M_ACCP      =   2, // ac-comp
	M_ADFM      =   3, // add-from
	M_ADLN      =   4, // addr-lines
	M_ADTO      =   5, // add-to
	M_AGER      =   6, // age-rate
	M_ALLW      =   7, // allowance
	M_ALTI      =   8, // alt
	M_ALTR      =   9, // alt-rate
	M_AMCP      =  10, // am-comp
	M_AMCU      =  11, // am-coupl
	M_AMFQ      =  12, // am-freq
	M_AMMC      =  13, // ampl-mod-c
	M_AMMF      =  14, // ampl-mod-f
	M_AMPL      =  15, // ampl-mod
	M_AMSH      =  16, // am-shift
	M_AMSR      =  17, // am-source
	M_ANAC      =  18, // angle-accel
	M_ANAX      =  19, // angle-accel-x
	M_ANAY      =  20, // angle-accel-y
	M_ANAZ      =  21, // angle-accel-z
	M_ANGL      =  22, // angle
	M_ANGP      =  23, // angle-phi
	M_ANGT      =  24, // angle-theta
	M_ANGX      =  25, // angle-x
	M_ANGY      =  26, // angle-y
	M_ANGZ      =  27, // angle-z
	M_ANRT      =  28, // angle-rate
	M_ANRX      =  29, // angle-rate-x
	M_ANRY      =  30, // angle-rate-y
	M_ANRZ      =  31, // angle-rate-z
	M_ANSD      =  32, // ant-speed-dev
	M_ATMS      =  33, // atmos
	M_ATTE      =  34, // attenuation
	M_ATTN      =  35, // atten
	M_AUCO      =  36, // autocollimation
	M_BAND      =  37, // bandwidth
	M_BARP      =  38, // barometric-press
	M_BDTH      =  39, // beam-detection-threshold
	M_BITP      =  40, // bit-period
	M_BITR      =  41, // bit-rate
	M_BKPH      =  42, // back-porch
	M_BRAN      =  43, // boresight-angle
	M_BTRN      =  44, // bit-transition
	M_BURD      =  45, // burst-droop
	M_BURR      =  46, // burst-rep-rate
	M_BURS      =  47, // burst
	M_BUSM      =  48, // bus-mode
	M_BUSS      =  49, // bus-spec
	M_CAMP      =  50, // car-ampl
	M_CAPA      =  51, // cap
	M_CCOM      =  52, // count-command
	M_CDAT      =  53, // count-data
	M_CFRQ      =  54, // car-freq
	M_CHAN      =  55, // channel
	M_CHID      =  56, // channel-ident
	M_CHIT      =  57, // chan-integrity
	M_CHRM      =  58, // car-harmonics
	M_CLKS      =  59, // clock-source
	M_CMCH      =  60, // compare-ch
	M_CMDW      =  61, // command-word
	M_CMPL      =  62, // compl
	M_CMTO      =  63, // compare-to
	M_CMWB      =  64, // command-word-bit
	M_CMWV      =  65, // compare-wave
	M_COMD      =  66, // command
	M_COND      =  67, // conductance
	M_COUN      =  68, // count
	M_CPHS      =  69, // car-phase
	M_CPKN      =  70, // current-p-neg
	M_CPKP      =  71, // current-p-pos
	M_CPLG      =  72, // coupling
	M_CRSD      =  73, // car-resid
	M_CRSF      =  74, // crest-factor
	M_CSTS      =  75, // count-status
	M_CTRQ      =  76, // cutoff-freq
	M_CUPK      =  77, // current-p
	M_CUPP      =  78, // current-pp
	M_CUR0      =  79, // current-zero
	M_CUR1      =  80, // current-one
	M_CURA      =  81, // av-current
	M_CURI      =  82, // current-inst
	M_CURL      =  83, // current-lmt
	M_CURQ      =  84, // current-quies
	M_CURR      =  85, // current
	M_CURT      =  86, // current-trms
	M_CWLV      =  87, // cw-level
	M_DATA      =  88, // data
	M_DATL      =  89, // data-word-length
	M_DATP      =  90, // data-word-parity
	M_DATS      =  91, // data-word-sync
	M_DATT      =  92, // data-word-tr
	M_DATW      =  93, // data-word
	M_DBLI      =  94, // dbl-int
	M_DBND      =  95, // doppler-bandwidth
	M_DBRC      =  96, // debris-count
	M_DBRS      =  97, // debris-size
	M_DCOF      =  98, // dc-offset
	M_DDMD      =  99, // ddm
	M_DEEM      = 100, // de-emphasis
	M_DELA      = 101, // delay
	M_DEST      = 102, // destination
	M_DEWP      = 103, // dewpoint
	M_DFBA      = 104, // diff-boresight-angle
	M_DIFR      = 105, // differentiate
	M_DIFT      = 106, // differential-temp
	M_DIGS      = 107, // dig-spec
	M_DISP      = 108, // display
	M_DIST      = 109, // distance
	M_DIVG      = 110, // divergence
	M_DIVS      = 111, // divisions
	M_DMDS      = 112, // dominant-mod-sig
	M_DPFR      = 113, // doppler-freq
	M_DPSH      = 114, // doppler-shift
	M_DROO      = 115, // droop
	M_DSFC      = 116, // diss-factor
	M_DSTR      = 117, // distance-r
	M_DSTX      = 118, // distance-x
	M_DSTY      = 119, // distance-y
	M_DSTZ      = 120, // distance-z
	M_DTCT      = 121, // detector-count
	M_DTMD      = 122, // do-timed-digital
	M_DTOR      = 123, // distortion
	M_DTSC      = 124, // detector-scan
	M_DUTY      = 125, // duty-cycle
	M_DVPN      = 126, // dev-pneg
	M_DVPP      = 127, // dev-ppos
	M_DWBT      = 128, // data-word-bit
	M_EDLN      = 129, // end-line
	M_EDUT      = 130, // end-unit
	M_EFCY      = 131, // efficacy
	M_EFFI      = 132, // eff
	M_EGDR      = 133, // energy-distribution
	M_EINM      = 134, // event-interval
	M_ERRI      = 135, // error-index
	M_ERRO      = 136, // error
	M_EVAO      = 137, // event-after-occurrences
	M_EVDL      = 138, // event-delay
	M_EVEO      = 139, // event-each-occurrence
	M_EVEV      = 140, // event-every
	M_EVFO      = 141, // event-first-occurrence
	M_EVGB      = 142, // event-gated-by
	M_EVGF      = 143, // event-gate-from
	M_EVGR      = 144, // event-gate-forever
	M_EVGT      = 145, // event-gate-to
	M_EVOU      = 146, // event-out
	M_EVSB      = 147, // event-sync-bit
	M_EVSF      = 148, // event-sync-freq
	M_EVSL      = 149, // event-slope
	M_EVSW      = 150, // event-sync-word
	M_EVTF      = 151, // event-time-from
	M_EVTI      = 152, // event-indicator
	M_EVTR      = 153, // event-time-forever
	M_EVTT      = 154, // event-time-to
	M_EVUN      = 155, // event-until
	M_EVWH      = 156, // event-when
	M_EVXE      = 157, // event-sense
	M_EVXM      = 158, // event-stim
	M_EXAE      = 159, // except at every
	M_EXNM      = 160, // exchange-number
	M_EXPO      = 161, // exponent
	M_FALL      = 162, // fall-time
	M_FCLN      = 163, // focal-length
	M_FCNT      = 164, // frame-count
	M_FDST      = 165, // field-strength
	M_FDVW      = 166, // field-of-view
	M_FIAL      = 167, // first-active-line
	M_FILT      = 168, // filter
	M_FLTC      = 169, // fault-count
	M_FLTS      = 170, // fault-test
	M_FLUT      = 171, // fluid-type
	M_FMCP      = 172, // fm-comp
	M_FMCU      = 173, // fm-coupl
	M_FMFQ      = 174, // fm-freq
	M_FMSR      = 175, // fm-source
	M_FRCE      = 176, // force
	M_FRCR      = 177, // force-rate
	M_FREQ      = 178, // freq
	M_FRMT      = 179, // format
	M_FRQ0      = 180, // freq-zero
	M_FRQ1      = 181, // freq-one
	M_FRQD      = 182, // freq-dev
	M_FRQP      = 183, // freq-pairing
	M_FRQQ      = 184, // freq-quies
	M_FRQR      = 185, // freq-ratio
	M_FRQW      = 186, // freq-window
	M_FUEL      = 187, // fuel-supply
	M_FXDN      = 188, // flux-dens
	M_FXIP      = 189, // flux-dens-in-phase
	M_FXQD      = 190, // flux-dens-quad
	M_GAMA      = 191, // gamma
	M_GSLP      = 192, // glide-slope
	M_HAPW      = 193, // harm-power
	M_HARM      = 194, // harmonics
	M_HARN      = 195, // harm-number
	M_HARP      = 196, // harm-phase
	M_HARV      = 197, // harm-voltage
	M_HFOV      = 198, // h-field-of-view
	M_HIZZ      = 199, // hiz
	M_HLAE      = 200, // h-los-align-error
	M_HMDF      = 201, // hi-mod-freq
	M_HRAG      = 202, // h-reference-angle
	M_HSRM      = 203, // h-sensor-resolution-min
	M_HTAG      = 204, // h-target-angle
	M_HTOF      = 205, // h-target-offset
	M_HUMY      = 206, // humidity
	M_IASP      = 207, // ias
	M_ICWB      = 208, // invalid-command-word-bit
	M_IDSE      = 209, // ident-sig-ep
	M_IDSF      = 210, // ident-sig-freq
	M_IDSG      = 211, // ident-sig
	M_IDSM      = 212, // ident-sig-mod
	M_IDWB      = 213, // invalid-data-word-bit
	M_IJIT      = 214, // int-jitter
	M_ILLU      = 215, // illum
	M_INDU      = 216, // ind
	M_INTG      = 217, // integrate
	M_INTL      = 218, // interval
	M_IRAT      = 219, // int-rate
	M_ISTI      = 220, // illegal-state-indicator
	M_ISWB      = 221, // invalid-status-word-bit
	M_ITER      = 222, // iterate
	M_ITRO      = 223, // intensity-ratio
	M_IVCW      = 224, // invalid-command-word
	M_IVDL      = 225, // invalid-data-word-length
	M_IVDP      = 226, // invalid-data-word-parity
	M_IVDS      = 227, // invalid-data-word-sync
	M_IVDT      = 228, // invalid-data-word-tr
	M_IVDW      = 229, // invalid-data-word
	M_IVMG      = 230, // invalid-message-gap
	M_IVOA      = 231, // invalid-one-amplitude
	M_IVRT      = 232, // invalid-response-time
	M_IVSW      = 233, // invalid-status-word
	M_IVWC      = 234, // invalid-word-count
	M_IVWG      = 235, // invalid-word-gap
	M_IVWL      = 236, // invalid-word-length
	M_IVZA      = 237, // invalid-zero-amplitude
	M_IVZC      = 238, // invalid-zero-crossing
	M_LDFM      = 239, // load-from
	M_LDTO      = 240, // load-to
	M_LDVW      = 241, // load-wave
	M_LINE      = 242, // line
	M_LIPF      = 243, // lines-per-frame
	M_LMDF      = 244, // lo-mod-freq
	M_LMIN      = 245, // lum-int
	M_LOCL      = 246, // localizer
	M_LRAN      = 247, // lst-reference-angle
	M_LSAE      = 248, // los-align-error
	M_LSTG      = 249, // laser-stage
	M_LUMF      = 250, // lum-flux
	M_LUMI      = 251, // luminance
	M_LUMT      = 252, // lum-temp
	M_MAGB      = 253, // mag-bearing
	M_MAGR      = 254, // mag-bearing-rate
	M_MAMP      = 255, // mod-ampl
	M_MANI      = 256, // manual-intervention
	M_MASF      = 257, // mass-flow
	M_MASK      = 258, // mask-one
	M_MATH      = 259, // math
	M_MAXT      = 260, // max-time
	M_MDPN      = 261, // mod-pneg
	M_MDPP      = 262, // mod-ppos
	M_MDSC      = 263, // mod-source
	M_MGAP      = 264, // message-gap
	M_MMOD      = 265, // mean-mod
	M_MODD      = 266, // mod-dist
	M_MODE      = 267, // mode
	M_MODF      = 268, // mod-freq
	M_MODO      = 269, // mod-offset
	M_MODP      = 270, // mod-phase
	M_MPFM      = 271, // multp-from
	M_MPTO      = 272, // multp-to
	M_MRCO      = 273, // min-resolv-contrast
	M_MRKB      = 274, // marker-beacon
	M_MRTD      = 275, // min-resolv-temp-diff
	M_MSKZ      = 276, // mask-zero
	M_MSNR      = 277, // minimum-sense-rate
	M_MTFD      = 278, // mtf-direction
	M_MTFP      = 279, // mtf-freq-points
	M_MTFU      = 280, // modulation-transfer-function
	M_NEDT      = 281, // noise-eq-diff-temp
	M_NEGS      = 282, // neg-slope
	M_NHAR      = 283, // non-harmonics
	M_NLIN      = 284, // non-lin
	M_NOAD      = 285, // noise-ampl-dens
	M_NOAV      = 286, // noise-av
	M_NOIS      = 287, // noise
	M_NOPD      = 288, // noise-pwr-dens
	M_NOPK      = 289, // noise-p
	M_NOPP      = 290, // noise-pp
	M_NOTR      = 291, // noise-trms
	M_NPWT      = 292, // neg-pulse-width
	M_OAMP      = 293, // one-amplitude
	M_OTMP      = 294, // oper-temp
	M_OVER      = 295, // overshoot
	M_P3DV      = 296, // p3-dev
	M_P3LV      = 297, // p3-level
	M_PAMP      = 298, // p-ampl
	M_PANG      = 299, // phase-angle
	M_PARE      = 300, // parity-even
	M_PARO      = 301, // parity-odd
	M_PATH      = 302, // path
	M_PATT      = 303, // pattern
	M_PCCU      = 304, // pac-coupl
	M_PCLS      = 305, // pulse-class
	M_PCSR      = 306, // pac-source
	M_PDEV      = 307, // phase-dev
	M_PDGN      = 308, // peak-degen
	M_PDRP      = 309, // pair-droop
	M_PERI      = 310, // period
	M_PHPN      = 311, // phase-pneg
	M_PHPP      = 312, // phase-ppos
	M_PJIT      = 313, // phase-jit
	M_PKDV      = 314, // peak-dev
	M_PLAN      = 315, // pla
	M_PLAR      = 316, // pla-rate
	M_PLEG      = 317, // pulse-energy
	M_PLID      = 318, // pulse-ident
	M_PLSE      = 319, // pulses-excl
	M_PLSI      = 320, // pulses-incl
	M_PLWD      = 321, // pulse-width
	M_PMCU      = 322, // pm-coupl
	M_PMFQ      = 323, // pm-freq
	M_PMSR      = 324, // pm-source
	M_PODN      = 325, // power-dens
	M_POSI      = 326, // position
	M_POSS      = 327, // pos-slope
	M_POWA      = 328, // power-av
	M_POWP      = 329, // power-p
	M_POWR      = 330, // power
	M_PPOS      = 331, // pulse-posn
	M_PPWT      = 332, // pos-pulse-width
	M_PRCD      = 333, // proceed
	M_PRDF      = 334, // power-diff
	M_PRFR      = 335, // prf
	M_PRIO      = 336, // priority
	M_PROA      = 337, // press-osc-ampl
	M_PROF      = 338, // press-osc-freq
	M_PRSA      = 339, // press-a
	M_PRSG      = 340, // press-g
	M_PRSR      = 341, // press-rate
	M_PSHI      = 342, // phase-shift
	M_PSHT      = 343, // preshoot
	M_PSPC      = 344, // pair-spacing
	M_PSPE      = 345, // pulse-spect
	M_PSPT      = 346, // pulse-spect-threshold
	M_PWRL      = 347, // pwr-lmt
	M_QFAC      = 348, // q
	M_QUAD      = 349, // quad
	M_RADL      = 350, // radial
	M_RADR      = 351, // radial-rate
	M_RDNC      = 352, // radiance
	M_REAC      = 353, // reactance
	M_REFF      = 354, // ref-freq
	M_REFI      = 355, // ref-inertial
	M_REFM      = 356, // reference-mirror-size
	M_REFP      = 357, // ref-power
	M_REFR      = 358, // ref-res
	M_REFU      = 359, // ref-uut
	M_REFV      = 360, // ref-volt
	M_REFX      = 361, // ref
	M_RELB      = 362, // rel-bearing
	M_RELH      = 363, // relative-humidity
	M_RELW      = 364, // relative-wind
	M_REPT      = 365, // repeat
	M_RESB      = 366, // resolution-bandwidth
	M_RESI      = 367, // res
	M_RESP      = 368, // resp
	M_RESR      = 369, // res-ratio
	M_RING      = 370, // ringing
	M_RISE      = 371, // rise-time
	M_RLBR      = 372, // rel-bearing-rate
	M_RLVL      = 373, // radiance-level-count
	M_RMNS      = 374, // ramp-neg-slope
	M_RMOD      = 375, // ranging-mode
	M_RMPS      = 376, // ramp-pos-slope
	M_ROUN      = 377, // rounding
	M_RPDV      = 378, // range-pulse-dev
	M_RPEC      = 379, // range-pulse-echo
	M_RPHF      = 380, // ref-phase-freq
	M_RPLD      = 381, // ref-pulses-dev
	M_RPLE      = 382, // reply-eff
	M_RPLI      = 383, // ref-pulses-incl
	M_RPLX      = 384, // ref-pulses-excl
	M_RSPH      = 385, // resp-hiz
	M_RSPO      = 386, // resp-one
	M_RSPT      = 387, // response-time
	M_RSPZ      = 388, // resp-zero
	M_RTRS      = 389, // rotor-speed
	M_SASP      = 390, // sample-spacing
	M_SATM      = 391, // sample-time
	M_SBCF      = 392, // sub-car-freq
	M_SBCM      = 393, // sub-car-mod
	M_SBEV      = 394, // strobe-to-event
	M_SBFM      = 395, // subtract-from
	M_SBTO      = 396, // subtract-to
	M_SCNT      = 397, // sample-count
	M_SDEL      = 398, // sense-delay
	M_SERL      = 399, // serial-lsb-first
	M_SERM      = 400, // serial-msb-first
	M_SESA      = 401, // sensor-aperture
	M_SETT      = 402, // settle-time
	M_SGNO      = 403, // sig-noise
	M_SGTF      = 404, // sig-transfer-function
	M_SHFS      = 405, // shaft-speed
	M_SIMU      = 406, // do-simultaneous
	M_SITF      = 407, // sys-intens-transfer-function
	M_SKEW      = 408, // skew-time
	M_SLEW      = 409, // slew-rate
	M_SLRA      = 410, // slant-range-accel
	M_SLRG      = 411, // slant-range
	M_SLRR      = 412, // slant-range-rate
	M_SLSD      = 413, // sls-dev
	M_SLSL      = 414, // sls-level
	M_SMAV      = 415, // sample-av
	M_SMPL      = 416, // sample
	M_SMPW      = 417, // sample-width
	M_SMTH      = 418, // smooth
	M_SNAD      = 419, // sinad
	M_SNSR      = 420, // sense-rate
	M_SPCG      = 421, // spacing
	M_SPED      = 422, // speed
	M_SPGR      = 423, // spec-grav
	M_SPTM      = 424, // spec-temp
	M_SQD1      = 425, // sqtr-dist-1
	M_SQD2      = 426, // sqtr-dist-2
	M_SQD3      = 427, // sqtr-dist-3
	M_SQTD      = 428, // sqtr-dist
	M_SQTR      = 429, // sqtr-rate
	M_SRFR      = 430, // sensor-freq
	M_SSMD      = 431, // sensitivity-mode
	M_STAT      = 432, // status
	M_STBM      = 433, // satellite-beam
	M_STIM      = 434, // stim
	M_STLN      = 435, // start-line
	M_STMH      = 436, // stim-hiz
	M_STMO      = 437, // stim-one
	M_STMP      = 438, // static-temp
	M_STMR      = 439, // stim-rate
	M_STMZ      = 440, // stim-zero
	M_STOP      = 441, // stop
	M_STPA      = 442, // static-press-a
	M_STPG      = 443, // static-press-g
	M_STPR      = 444, // static-press-rate
	M_STPT      = 445, // set-of-points
	M_STRD      = 446, // standard
	M_STRT      = 447, // start
	M_STUT      = 448, // start-unit
	M_STWD      = 449, // status-word
	M_SUSP      = 450, // susceptance
	M_SVCP      = 451, // save-comp
	M_SVFM      = 452, // save-from
	M_SVTO      = 453, // save-to
	M_SVWV      = 454, // save-wave
	M_SWBT      = 455, // status-word-bit
	M_SWPT      = 456, // sweep-time
	M_SWRA      = 457, // swr
	M_SYDL      = 458, // sync-delay
	M_SYEV      = 459, // sync-to-event
	M_SYNC      = 460, // sync
	M_TASP      = 461, // tas
	M_TASY      = 462, // time-asym
	M_TCAP      = 463, // temp-coeff-cap
	M_TCUR      = 464, // temp-coeff-current
	M_TEFC      = 465, // test-freq-count
	M_TEMP      = 466, // temp
	M_TEQL      = 467, // test-equip-listener
	M_TEQT      = 468, // test-equip-talker
	M_TGMD      = 469, // trigger-mode
	M_TGPL      = 470, // target-polarity
	M_TGTA      = 471, // target-range-accel
	M_TGTD      = 472, // target-range
	M_TGTH      = 473, // target-threshold
	M_TGTP      = 474, // target-type
	M_TGTR      = 475, // target-range-rate
	M_THRT      = 476, // thrust
	M_TIEV      = 477, // time-every
	M_TILT      = 478, // tilt
	M_TIME      = 479, // time
	M_TIMP      = 480, // test-equip-imp
	M_TIND      = 481, // temp-coeff-ind
	M_TIUN      = 482, // time-until
	M_TIWH      = 483, // time-when
	M_TJIT      = 484, // time-jit
	M_TLAX      = 485, // tilt-axis
	M_TMON      = 486, // test-equip-monitor
	M_TOPA      = 487, // total-press-a
	M_TOPG      = 488, // total-press-g
	M_TOPR      = 489, // total-press-rate
	M_TORQ      = 490, // torque
	M_TPHD      = 491, // three-phase-delta
	M_TPHY      = 492, // three-phase-wye
	M_TREA      = 493, // temp-coeff-react
	M_TRES      = 494, // temp-coeff-res
	M_TRGS      = 495, // trig-source
	M_TRIG      = 496, // trig
	M_TRLV      = 497, // trig-level
	M_TRN0      = 498, // trans-zero
	M_TRN1      = 499, // trans-one
	M_TRNP      = 500, // trans-period
	M_TRNS      = 501, // trans-sync
	M_TROL      = 502, // test-equip-role
	M_TRSL      = 503, // trig-slope
	M_TRUE      = 504, // true
	M_TRUN      = 505, // timer-until
	M_TRWH      = 506, // timer-when
	M_TSAC      = 507, // test-area-count
	M_TSCC      = 508, // test-chan-count
	M_TSIM      = 509, // test-equip-simulate
	M_TSPC      = 510, // test-point-count
	M_TSTF      = 511, // test-field
	M_TTMP      = 512, // total-temp
	M_TVOL      = 513, // temp-coeff-volt
	M_TYPE      = 514, // type
	M_UNDR      = 515, // undershoot
	M_UNFY      = 516, // uniformity
	M_UNIT      = 517, // unit
	M_UUPL      = 518, // units-per-line
	M_UUTL      = 519, // uut-listener
	M_UUTT      = 520, // uut-talker
	M_VALU      = 521, // value
	M_VBAC      = 522, // vibration-accel
	M_VBAN      = 523, // video-bandwidth
	M_VBAP      = 524, // vibration-ampl-p
	M_VBPP      = 525, // vibration-ampl-pp
	M_VBRT      = 526, // vibration-rate
	M_VBTR      = 527, // vibration-ampl-trms
	M_VDIV      = 528, // volt-per-div
	M_VEAO      = 529, // event-after-occurrences-value
	M_VEDL      = 530, // event-delay-value
	M_VEEO      = 531, // event-each-occurrence-value
	M_VEFO      = 532, // event-first-occurrence-value
	M_VEGF      = 533, // event-gate-for
	M_VETF      = 534, // event-time-for
	M_VFOV      = 535, // v-field-of-view
	M_VINS      = 536, // voltage-inst
	M_VIST      = 537, // video-sync-type
	M_VLAE      = 538, // v-los-align-error
	M_VLAV      = 539, // av-voltage
	M_VLPK      = 540, // voltage-p
	M_VLPP      = 541, // voltage-pp
	M_VLT0      = 542, // voltage-zero
	M_VLT1      = 543, // voltage-one
	M_VLTL      = 544, // volt-lmt
	M_VLTQ      = 545, // voltage-quies
	M_VLTR      = 546, // voltage-ramped
	M_VLTS      = 547, // voltage-stepped
	M_VOLF      = 548, // volume-flow
	M_VOLR      = 549, // voltage-ratio
	M_VOLT      = 550, // voltage
	M_VPHF      = 551, // var-phase-freq
	M_VPHM      = 552, // var-phase-mod
	M_VPKN      = 553, // voltage-p-neg
	M_VPKP      = 554, // voltage-p-pos
	M_VRAG      = 555, // v-reference-angle
	M_VRMS      = 556, // voltage-trms
	M_VSRM      = 557, // v-sensor-resolution-min
	M_VTAG      = 558, // v-target-angle
	M_VTOF      = 559, // v-target-offset
	M_WAIT      = 560, // wait
	M_WAVE      = 561, // wave-length
	M_WDLN      = 562, // word-length
	M_WDRT      = 563, // word-rate
	M_WGAP      = 564, // word-gap
	M_WILD      = 565, // wild
	M_WIND      = 566, // wind-speed
	M_WRDC      = 567, // word-count
	M_WTRN      = 568, // word-transition
	M_XAGR      = 569, // x-angle-of-regard
	M_XBAG      = 570, // x-boresight-angle
	M_XTAR      = 571, // x-target-angle
	M_YAGR      = 572, // y-angle-of-regard
	M_YBAG      = 573, // y-boresight-angle
	M_YTAR      = 574, // y-target-angle
	M_ZAMP      = 575, // zero-amplitude
	M_ZCRS      = 576, // zero-crossing
	M_ZERO      = 577, // zero-index
	M__CNT      = 578, // symbol count
};
//
//	MODULETYPES
//
enum enumTyxModuletypes {
	T_ACS       =   1, // name not available
	T_API       =   2, // name not available
	T_ARB       =   3, // name not available
	T_ASA       =   4, // name not available
	T_DCS       =   5, // name not available
	T_DIG       =   6, // name not available
	T_DMM       =   7, // name not available
	T_DWG       =   8, // name not available
	T_FNG       =   9, // name not available
	T_FTM       =  10, // name not available
	T_MBT       =  11, // name not available
	T_MFU       =  12, // name not available
	T_MTR       =  13, // name not available
	T_PAT       =  14, // name not available
	T_PCM       =  15, // name not available
	T_PLG       =  16, // name not available
	T_PSS       =  17, // name not available
	T_PWM       =  18, // name not available
	T_QAL       =  19, // name not available
	T_RSV       =  20, // name not available
	T_RSY       =  21, // name not available
	T_SNG       =  22, // name not available
	T_SRS       =  23, // name not available
	T_VDG       =  24, // name not available
	T__CNT      =  25, // symbol count
};
//
//	DIMS-A
//
enum enumTyxDimsA {
	D_1553A     =   1, // mil-1553a
	D_1553B     =   2, // mil-1553b
	D_ALLLS     =   3, // all-listener
	D_AMI       =   4, // ami
	D_AR429     =   5, // arinc-429
	D_ARDC      =   6, // ardc
	D_BIP       =   7, // bip
	D_CONMD     =   8, // con-mode
	D_CONRT     =   9, // con-rt
	D_CSM       =  10, // csm
	D_CSN       =  11, // csn
	D_CSOC      =  12, // consecutive-occurrences
	D_HDB       =  13, // hdb
	D_ICAN      =  14, // ican
	D_ICAO      =  15, // icao
	D_IEEE488   =  16, // ieee-488
	D_LNGTH     =  17, // length
	D_MASTR     =  18, // master
	D_MIP       =  19, // mip
	D_MONTR     =  20, // monitor
	D_NRZ       =  21, // nrz
	D_OFF       =  22, // off
	D_ON        =  23, // on
	D_PARA      =  24, // parallel
	D_PRIM      =  25, // primary
	D_PRTY      =  26, // parity
	D_REDT      =  27, // redundant
	D_RS232     =  28, // rs-232
	D_RS422     =  29, // rs-422
	D_RTCON     =  30, // rt-con
	D_RTRT      =  31, // rt-rt
	D_RZ        =  32, // rz
	D_SERL      =  33, // serial-lsb-first
	D_SERM      =  34, // serial-msb-first
	D_SLAVE     =  35, // slave
	D_SYNC      =  36, // sync
	D_TLKLS     =  37, // talker-listener
	D_TR        =  38, // t-r
	D_WADC      =  39, // wadc
	D__CNT      =  40, // symbol count
};
//
//	DIMS-B
//
enum enumTyxDimsB {
	R__CNT      =   1, // symbol count
};
#endif // _LEXKEY_H_
