VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cRFREC"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
DefInt A-Z


Public Sub SendMsg(sMsg As String)
   MsgBox ("RFREC SendMsg not implemented!")
End Sub

Public Function sReadMsg(sMsg As String) As String
 ' RF Recorder

   MsgBox ("RFREC sReadMsg not implemented!")
End Function

